// app/src/app/components/ledger/account-ledger/account-ledger.component.ts
import { CommonModule } from '@angular/common';
import type { ElementRef, OnInit } from '@angular/core';
import {
    ChangeDetectionStrategy,
    Component,
    computed,
    inject,
    input,
    signal,
    viewChild
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import type { ISODateString, ISplit, ITransaction } from '@core';
import { AccountType, KnownCategory, Money, TransactionStatus } from '@core';
import {
    Banknote,
    Calendar,
    CreditCard,
    Landmark,
    LucideAngularModule,
    Plus,
    Search,
    Wallet
} from 'lucide-angular';

import type { IReconciliationMatch } from '@core';
import { QIFParser } from '../../../core/parsers/QIFParser';
import { LedgerStore } from '../../../services/ledger-store/ledger.store';
import { PostHogService } from '../../../services/posthog/posthog.service';
import { SyncIndicatorComponent } from '../../sync/sync-indicator/sync-indicator.component';
import { ReconciliationDialogComponent } from '../reconciliation-dialog/reconciliation-dialog.component';
import { TransactionTableComponent } from '../transaction-table/transaction-table.component';

@Component({
    selector: 'account-ledger',
    standalone: true,
    imports: [
        CommonModule,
        FormsModule,
        RouterLink,
        LucideAngularModule,
        TransactionTableComponent,
        SyncIndicatorComponent,
        ReconciliationDialogComponent
    ],
    templateUrl: './account-ledger.component.html',
    styleUrls: ['./account-ledger.component.css'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class AccountLedgerComponent implements OnInit {
    private readonly ledgerStore = inject(LedgerStore);
    private readonly posthogService = inject(PostHogService);

    // Inputs
    readonly initialAccountId = input<string | null>(null);

    // State
    readonly activeAccountId = signal<string | null>(null);
    readonly isImporting = signal<boolean>(false);

    // Quick Add Form
    readonly entryPayee = signal<string>('');
    readonly entryAmount = signal<string>('');
    readonly entryDate = signal<string>(new Date().toISOString().split('T')[0] ?? '');
    readonly entryMemo = signal<string>('');
    readonly manualSplits = signal<Array<ISplit>>(new Array<ISplit>());

    // Reconciliation Dialog
    readonly reconciliationOpen = signal<boolean>(false);
    readonly reconciliationMatches = signal<Array<IReconciliationMatch>>([]);

    // Temp for Template
    readonly fileInput = viewChild<ElementRef<HTMLInputElement>>('fileInput');

    // Computed
    readonly accounts = this.ledgerStore.accounts;
    readonly transactions = this.ledgerStore.transactions;

    readonly filteredTransactions = computed(() => {
        const accId = this.activeAccountId();
        const allTxs = this.transactions();
        if (!accId) return allTxs;
        return allTxs.filter(tx => tx.accountId === accId);
    });

    readonly clearedBalance = computed(() => {
        return this.filteredTransactions()
            .filter(tx => tx.status === TransactionStatus.Cleared)
            .reduce((sum, tx) => sum + tx.totalAmount, 0);
    });

    readonly pendingBalance = computed(() => {
        return this.filteredTransactions()
            .filter(tx => tx.status === TransactionStatus.Pending)
            .reduce((sum, tx) => sum + tx.totalAmount, 0);
    });

    ngOnInit(): void {
        this.activeAccountId.set(this.initialAccountId());
    }

    async handleQuickAdd(): Promise<void> {
        const payee = this.entryPayee();
        const amountStr = this.entryAmount();
        if (!payee || !amountStr) return;

        const amountCents = Money.dollarsToCents(parseFloat(amountStr));
        const now = new Date().toISOString();

        const tx: ITransaction = {
            id: `tx-${Date.now()}`,
            accountId: this.activeAccountId() ?? 'default',
            payeeId: 'manual', // Simplified for now
            date: this.entryDate() as ISODateString,
            payee: payee,
            memo: this.entryMemo(),
            totalAmount: amountCents,
            status: TransactionStatus.Cleared,
            checkNumber: null,
            importHash: `manual-${Date.now()}`,
            splits:
                this.manualSplits().length > 0
                    ? this.manualSplits()
                    : new Array<ISplit>({
                          id: `split-${Date.now()}`,
                          amount: amountCents,
                          memo: this.entryMemo(),
                          categoryId: KnownCategory.Uncategorized
                      }),
            createdAt: now as ISODateString,
            updatedAt: now as ISODateString
        };

        await this.ledgerStore.addTransaction(tx);
        this.posthogService.posthog.capture('transaction_added', {
            account_id: this.activeAccountId(),
            is_split: this.manualSplits().length > 0,
            amount_cents: amountCents
        });

        // Reset form
        this.entryPayee.set('');
        this.entryAmount.set('');
        this.entryMemo.set('');
        this.manualSplits.set(new Array<ISplit>());
    }

    formatCurrency(amount: number): string {
        return Money.formatCurrency(amount);
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    getAccountIcon(type: AccountType): any {
        switch (type) {
            case AccountType.Checking:
                return Landmark;
            case AccountType.Savings:
                return Banknote;
            case AccountType.Credit:
                return CreditCard;
            case AccountType.Cash:
                return Wallet;
            default:
                return Landmark;
        }
    }

    triggerImport(): void {
        this.fileInput()?.nativeElement.click();
    }

    onFileSelected(event: Event): void {
        const input = event.target as HTMLInputElement;
        const file = input.files?.[0];
        if (!file) return;

        this.isImporting.set(true);

        const reader = new FileReader();
        reader.onload = async (e: ProgressEvent<FileReader>): Promise<void> => {
            try {
                const content = e.target?.result as string;
                const parser = new QIFParser();
                const parseResult = parser.parse(content);

                if (parseResult.errors.length > 0) {
                    console.warn('[Import] Parse errors:', parseResult.errors);
                }

                const accountId = this.activeAccountId() ?? 'default';
                const matches = await this.ledgerStore.reconcileTransactions(
                    parseResult.transactions,
                    accountId
                );

                this.reconciliationMatches.set(matches);
                this.reconciliationOpen.set(true);

                this.posthogService.posthog.capture('qif_import_parsed', {
                    transaction_count: parseResult.transactions.length,
                    error_count: parseResult.errors.length,
                    account_type: parseResult.accountType
                });
            } catch (err) {
                console.error('[Import] Failed to parse QIF file:', err);
            } finally {
                this.isImporting.set(false);
                // Reset the file input so the same file can be re-imported if needed
                if (input) input.value = '';
            }
        };

        reader.onerror = (): void => {
            console.error('[Import] FileReader error');
            this.isImporting.set(false);
        };

        reader.readAsText(file);
    }

    async handleReconciliationConfirmed(
        decisions: Record<number, 'import' | 'match' | 'ignore'>
    ): Promise<void> {
        const matches = this.reconciliationMatches();
        const accountId = this.activeAccountId() ?? 'default';
        const now = new Date().toISOString();
        const txsToImport: Array<ITransaction> = [];

        for (const [idxStr, decision] of Object.entries(decisions)) {
            const idx = parseInt(idxStr, 10);
            const match = matches[idx];
            if (!match) continue;

            if (decision === 'import') {
                const parsed = match.parsedTx;
                // Get or create payee
                const payee = await this.ledgerStore.getOrCreatePayee(parsed.payee);

                const tx: ITransaction = {
                    id: `tx-import-${Date.now()}-${idx}`,
                    accountId,
                    payeeId: payee.id,
                    date: parsed.date,
                    payee: parsed.payee,
                    memo: parsed.memo,
                    totalAmount: parsed.amount,
                    status: TransactionStatus.Cleared,
                    checkNumber: parsed.checkNumber,
                    importHash: parsed.importHash,
                    splits: [
                        {
                            id: `split-import-${Date.now()}-${idx}`,
                            amount: parsed.amount,
                            memo: parsed.memo,
                            categoryId: KnownCategory.Uncategorized
                        }
                    ],
                    createdAt: now as ISODateString,
                    updatedAt: now as ISODateString
                };
                txsToImport.push(tx);
            } else if (decision === 'match' && match.existingTxId) {
                // Mark matched transaction as Cleared
                const existingTx = this.transactions().find(t => t.id === match.existingTxId);
                if (existingTx) {
                    await this.ledgerStore.updateTransaction({
                        ...existingTx,
                        status: TransactionStatus.Cleared,
                        updatedAt: now as ISODateString
                    });
                }
            }
            // 'ignore' — do nothing
        }

        if (txsToImport.length > 0) {
            await this.ledgerStore.addTransactions(txsToImport);
        }

        this.posthogService.posthog.capture('qif_import_completed', {
            imported_count: txsToImport.length,
            total_decisions: Object.keys(decisions).length
        });
    }

    getAccountBalance(accId: string): number {
        return this.transactions()
            .filter(t => t.accountId === accId)
            .reduce((s, t) => s + t.totalAmount, 0);
    }

    // Lucide Icons
    readonly Landmark = Landmark;
    readonly Banknote = Banknote;
    readonly CreditCard = CreditCard;
    readonly Wallet = Wallet;
    readonly Plus = Plus;
    readonly Search = Search;
    readonly Calendar = Calendar;
}

<div class="flex h-full w-full gap-4 overflow-hidden">
    <input #fileInput type="file" (change)="onFileSelected($event)" accept=".qif" class="hidden" />

    <!-- Account Sidebar -->
    <aside class="w-64 flex flex-col gap-4 flex-none overflow-hidden pr-2">
        <div
            class="bg-surface-0 border border-surface-200 rounded-sm h-full flex flex-col overflow-hidden"
        >
            <div
                class="px-4 py-3 flex justify-between items-center border-b border-surface-200 bg-surface-100/30"
            >
                <h2 class="text-xs text-surface-500 font-bold uppercase tracking-widest">
                    Accounts
                </h2>
                <a routerLink="/accounts" class="text-primary hover:text-white transition-colors">
                    <lucide-icon [img]="Plus" class="w-3 h-3" />
                </a>
            </div>
            <div class="flex-1 overflow-y-auto p-2 space-y-1">
                @for (acc of accounts(); track acc.id) {
                    <div
                        (click)="activeAccountId.set(acc.id)"
                        (keydown.enter)="activeAccountId.set(acc.id)"
                        (keydown.space)="activeAccountId.set(acc.id)"
                        tabindex="0"
                        role="button"
                        class="p-2 rounded-sm cursor-pointer transition-all border outline-none focus:ring-1 focus:ring-primary"
                        [class]="{
                            'bg-primary/10 border-primary/30': activeAccountId() === acc.id,
                            'bg-transparent border-transparent hover:bg-surface-100/50':
                                activeAccountId() !== acc.id
                        }"
                    >
                        <div class="flex justify-between items-start mb-1">
                            <span
                                class="text-sm font-bold"
                                [class.text-primary]="activeAccountId() === acc.id"
                                [class.text-surface-800]="activeAccountId() !== acc.id"
                            >
                                {{ acc.name }}
                            </span>
                            <span class="text-[10px] text-surface-500 opacity-50">
                                <lucide-icon [img]="getAccountIcon(acc.type)" class="w-3.5 h-3.5" />
                            </span>
                        </div>
                        <div class="text-sm font-mono font-bold text-surface-500">
                            {{ formatCurrency(getAccountBalance(acc.id)) }}
                        </div>
                    </div>
                }
            </div>
            <div class="p-2 border-t border-surface-200 bg-surface-100/20">
                <a
                    routerLink="/recurring"
                    class="flex items-center gap-2 p-2 rounded-sm hover:bg-primary/10 transition-colors group"
                >
                    <lucide-icon
                        [img]="Calendar"
                        class="w-3.5 h-3.5 text-surface-500 group-hover:text-primary"
                    />
                    <span
                        class="text-[10px] font-black uppercase tracking-widest text-surface-500 group-hover:text-primary"
                    >
                        Bills & Scheduled
                    </span>
                </a>
            </div>
        </div>

        <div class="bg-surface-0 border border-surface-200 rounded-sm p-3">
            <div class="flex justify-between items-center mb-2">
                <span class="text-[10px] font-bold uppercase text-surface-500 tracking-wider">
                    Sync Engine
                </span>
                <sync-indicator />
            </div>
            <div class="flex flex-col gap-1.5">
                <div class="flex justify-between text-sm">
                    <span class="text-surface-500 uppercase font-bold tracking-tighter">
                        Cleared
                    </span>
                    <span class="font-mono text-emerald-900 font-bold">
                        {{ formatCurrency(clearedBalance()) }}
                    </span>
                </div>
                <div class="flex justify-between text-sm">
                    <span class="text-surface-500 uppercase font-bold tracking-tighter">
                        Pending
                    </span>
                    <span class="font-mono text-amber-500 font-bold">
                        {{ formatCurrency(pendingBalance()) }}
                    </span>
                </div>
            </div>
        </div>
    </aside>

    <!-- Main Ledger Area -->
    <div class="flex-1 flex flex-col gap-4 overflow-hidden">
        <div
            class="bg-surface-0 border border-surface-200 rounded-sm p-3 shadow-lg flex-none relative z-10"
        >
            <form
                (submit)="$event.preventDefault(); handleQuickAdd()"
                class="grid grid-cols-12 gap-3 items-end"
            >
                <div class="col-span-2">
                    <label
                        for="entry-date"
                        class="text-[10px] font-bold text-surface-500 uppercase block mb-1"
                    >
                        Date
                    </label>
                    <input
                        id="entry-date"
                        type="date"
                        [ngModel]="entryDate()"
                        (ngModelChange)="entryDate.set($event)"
                        name="date"
                        class="w-full h-7 text-xs font-mono uppercase px-2 bg-surface-50 border border-surface-200 rounded-md focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                </div>
                <div class="col-span-3">
                    <label
                        for="entry-payee"
                        class="text-[10px] font-bold text-surface-500 uppercase block mb-1"
                    >
                        Payee / Recipient
                    </label>
                    <div class="relative">
                        <lucide-icon
                            [img]="Search"
                            class="absolute left-2 top-1.5 w-3 h-3 text-surface-500"
                        />
                        <input
                            id="entry-payee"
                            type="text"
                            placeholder="Who did you pay?"
                            [ngModel]="entryPayee()"
                            (ngModelChange)="entryPayee.set($event)"
                            name="payee"
                            class="w-full h-7 pl-7 text-sm bg-surface-50 border border-surface-200 rounded-md focus:outline-none focus:ring-1 focus:ring-primary"
                        />
                    </div>
                </div>
                <div class="col-span-2">
                    <label
                        for="entry-amount"
                        class="text-[10px] font-bold text-surface-500 uppercase block mb-1"
                    >
                        Amount
                    </label>
                    <input
                        id="entry-amount"
                        type="number"
                        step="0.01"
                        placeholder="0.00"
                        [ngModel]="entryAmount()"
                        (ngModelChange)="entryAmount.set($event)"
                        name="amount"
                        class="w-full h-7 text-sm font-mono text-emerald-900 px-2 bg-surface-50 border border-surface-200 rounded-md focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                </div>
                <div class="col-span-3">
                    <label
                        for="entry-memo"
                        class="text-[10px] font-bold text-surface-500 uppercase block mb-1"
                    >
                        Memo / Description
                    </label>
                    <input
                        id="entry-memo"
                        type="text"
                        placeholder="What was it for?"
                        [ngModel]="entryMemo()"
                        (ngModelChange)="entryMemo.set($event)"
                        name="memo"
                        class="w-full h-7 text-sm px-2 bg-surface-50 border border-surface-200 rounded-md focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                </div>
                <div class="col-span-2 flex gap-2">
                    <button
                        type="submit"
                        class="flex-1 text-xs font-black uppercase h-7 bg-primary text-white rounded-md hover:bg-primary/90 transition-colors"
                    >
                        Record
                    </button>
                    <button
                        type="button"
                        class="px-2 text-xs uppercase font-bold h-7 border border-surface-200 bg-surface-50 rounded-md hover:bg-surface-100 transition-colors"
                        [class]="{ 'bg-primary/10 border-primary': manualSplits().length > 0 }"
                    >
                        {{
                            manualSplits().length > 0 ? manualSplits().length + ' Splits' : 'Split'
                        }}
                    </button>
                </div>
            </form>
        </div>

        <div class="flex items-center justify-between flex-none px-1">
            <div class="flex gap-2">
                <button
                    (click)="triggerImport()"
                    [disabled]="isImporting()"
                    class="h-7 px-3 text-xs font-black uppercase bg-primary/10 border border-primary/20 text-primary rounded-md hover:bg-primary/20 transition-colors"
                >
                    {{ isImporting() ? 'Processing QIF...' : 'Import Data' }}
                </button>
                <button
                    class="h-7 px-3 text-xs font-black uppercase border border-surface-200 bg-surface-50 rounded-md hover:bg-surface-100 transition-colors"
                >
                    Reconcile
                </button>
            </div>
        </div>

        <div
            class="bg-surface-0 border border-surface-200 rounded-sm flex-1 min-h-0 relative overflow-hidden flex flex-col group"
        >
            @if (isImporting()) {
                <div
                    class="absolute inset-0 bg-surface-50/80 z-20 flex items-center justify-center backdrop-blur-sm"
                >
                    <div class="flex flex-col items-center gap-3">
                        <div
                            class="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"
                        ></div>
                        <p class="text-sm font-bold text-primary uppercase tracking-[0.2em]">
                            Processing Ledger Data...
                        </p>
                    </div>
                </div>
            }
            <transaction-table [data]="filteredTransactions()" />
        </div>
    </div>
</div>

<reconciliation-dialog
    [(isOpen)]="reconciliationOpen"
    [matches]="reconciliationMatches()"
    (confirmed)="handleReconciliationConfirmed($event)"
/>

// apps/web/src/components/ledger/AccountLedger.tsx
'use client';

import { useState, useRef, useMemo } from 'react';
import { useLedgerStore } from '@/store/ledgerStore';
import {
    type ITransaction,
    type ISplit,
    type ISODateString,
    type IAccount,
    type IPayee,
    type IQIFParseResult,
    TransactionStatus,
    Money,
    QIFParser,
    AccountType,
    KnownCategory,
} from '@path-logic/core';
import { TransactionTable } from '@/components/ledger/TransactionTable';
import { SplitEntryDialog } from '@/components/ledger/SplitEntryDialog';
import { cn } from '@/lib/utils';
import { Landmark, Banknote, CreditCard, Wallet, Plus, Search, Calendar } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { SyncIndicator } from '@/components/sync/SyncIndicator';
import { ReconciliationDialog } from './ReconciliationDialog';
import { type IReconciliationMatch } from '@/lib/sync/ReconciliationEngine';
import { Card } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import Link from 'next/link';
import {
    ContextMenu,
    ContextMenuContent,
    ContextMenuItem,
    ContextMenuTrigger,
    ContextMenuSeparator,
    ContextMenuLabel,
} from '@/components/ui/context-menu';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import { AccountEditForm } from '@/components/accounts/AccountEditForm';

interface IAccountLedgerProps {
    initialAccountId?: string | null;
}

export function AccountLedger({ initialAccountId = null }: IAccountLedgerProps): React.JSX.Element {
    const {
        accounts,
        transactions,
        addTransaction,
        addTransactions,
        getOrCreatePayee,
        updateAccount,
        softDeleteAccount,
        reconcileTransactions,
    } = useLedgerStore();

    const [isImporting, setIsImporting] = useState<boolean>(false);
    const [activeAccountId, setActiveAccountId] = useState<string | null>(initialAccountId);
    const fileInputRef: React.RefObject<HTMLInputElement | null> = useRef<HTMLInputElement>(null);

    // Form state (MS Money Style)
    const [entryPayee, setEntryPayee] = useState<string>('');
    const [entryAmount, setEntryAmount] = useState<string>('');
    const [entryDate, setEntryDate] = useState<string>(
        new Date().toISOString().split('T')[0] || '',
    );
    const [entryMemo, setEntryMemo] = useState<string>('');
    const [isSplitDialogOpen, setIsSplitDialogOpen] = useState<boolean>(false);
    const [manualSplits, setManualSplits] = useState<Array<ISplit>>([]);
    const [accountToDelete, setAccountToDelete] = useState<string | null>(null);
    const [accountToEdit, setAccountToEdit] = useState<IAccount | null>(null);
    const [reconciliationMatches, setReconciliationMatches] = useState<Array<IReconciliationMatch>>(
        [],
    );
    const [isReconciliationOpen, setIsReconciliationOpen] = useState<boolean>(false);

    // Filter transactions for active account
    const filteredTransactions = useMemo(() => {
        if (!activeAccountId) return transactions;
        return transactions.filter(tx => tx.accountId === activeAccountId);
    }, [transactions, activeAccountId]);

    // Calculate balances
    const clearedBalance: number = filteredTransactions
        .filter((tx: ITransaction): boolean => tx.status === TransactionStatus.Cleared)
        .reduce((sum: number, tx: ITransaction): number => sum + tx.totalAmount, 0);

    const pendingBalance: number = filteredTransactions
        .filter((tx: ITransaction): boolean => tx.status === TransactionStatus.Pending)
        .reduce((sum: number, tx: ITransaction): number => sum + tx.totalAmount, 0);

    const handleImportClick = (): void => {
        fileInputRef.current?.click();
    };

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
        const file: File | undefined = e.target.files?.[0];
        if (!file) return;

        setIsImporting(true);
        const reader: FileReader = new FileReader();

        reader.onload = async (event: ProgressEvent<FileReader>): Promise<void> => {
            const content: string = event.target?.result as string;
            const parser: QIFParser = new QIFParser();
            const result: IQIFParseResult = parser.parse(content);

            if (result.transactions.length > 0) {
                const matches = await reconcileTransactions(
                    result.transactions,
                    activeAccountId || 'imported',
                );

                // If only exact matches, nothing to do
                const hasWork = matches.some(m => m.type !== 'exact');
                if (!hasWork) {
                    setIsImporting(false);
                    if (fileInputRef.current) fileInputRef.current.value = '';
                    return;
                }

                setReconciliationMatches(matches);
                setIsReconciliationOpen(true);
            }

            setIsImporting(false);
            if (fileInputRef.current) fileInputRef.current.value = '';
        };

        reader.readAsText(file);
    };

    const handleReconciliationConfirm = async (
        decisions: Record<number, 'import' | 'match' | 'ignore'>,
    ): Promise<void> => {
        const now: ISODateString = new Date().toISOString() as ISODateString;
        const toImport: Array<ITransaction> = [];

        for (const [idxStr, decision] of Object.entries(decisions)) {
            const idx = parseInt(idxStr, 10);
            const match = reconciliationMatches[idx];
            if (!match || decision !== 'import') continue;

            const pt = match.parsedTx;
            const payeeEntity = await getOrCreatePayee(pt.payee);

            const tx: ITransaction = {
                id: `import-${Date.now()}-${idx}`,
                accountId: activeAccountId || 'imported',
                payeeId: payeeEntity.id,
                date: pt.date,
                payee: pt.payee,
                memo: pt.memo || '',
                totalAmount: pt.amount,
                status: TransactionStatus.Cleared,
                checkNumber: pt.checkNumber || '',
                importHash: pt.importHash || '',
                splits:
                    pt.splits.length > 0
                        ? pt.splits.map(
                              (s, sIdx): ISplit => ({
                                  id: `split-${Date.now()}-${idx}-${sIdx}`,
                                  amount: s.amount,
                                  memo: s.memo || '',
                                  categoryId: s.category || KnownCategory.Uncategorized,
                              }),
                          )
                        : [
                              {
                                  id: `split-${Date.now()}-${idx}-0`,
                                  amount: pt.amount,
                                  memo: pt.memo || '',
                                  categoryId: KnownCategory.Uncategorized,
                              },
                          ],
                createdAt: now,
                updatedAt: now,
            };
            toImport.push(tx);
        }

        if (toImport.length > 0) {
            await addTransactions(toImport);
        }
        setIsReconciliationOpen(false);
    };

    const handleQuickAdd = async (e: React.FormEvent): Promise<void> => {
        e.preventDefault();
        if (!entryPayee || !entryAmount) return;

        const amountCents: number = Money.dollarsToCents(parseFloat(entryAmount));
        const now: ISODateString = new Date().toISOString() as ISODateString;
        const payeeEntity: IPayee = await getOrCreatePayee(entryPayee);

        const tx: ITransaction = {
            id: `tx-${Date.now()}`,
            accountId: activeAccountId || 'default',
            payeeId: payeeEntity.id,
            date: entryDate as ISODateString,
            payee: entryPayee,
            memo: entryMemo,
            totalAmount: amountCents,
            status: TransactionStatus.Cleared,
            checkNumber: null,
            importHash: `manual-${Date.now()}`,
            splits:
                manualSplits.length > 0
                    ? manualSplits
                    : [
                          {
                              id: `split-${Date.now()}`,
                              amount: amountCents,
                              memo: entryMemo,
                              categoryId: KnownCategory.Uncategorized,
                          },
                      ],
            createdAt: now,
            updatedAt: now,
        };

        await addTransaction(tx);
        setEntryPayee('');
        setEntryAmount('');
        setEntryMemo('');
        setManualSplits([]);
    };

    const handleSplitSave = (splits: Array<ISplit>, newTotal?: number): void => {
        setManualSplits(splits);
        if (newTotal !== undefined) {
            setEntryAmount(Money.centsToDollars(newTotal).toString());
        }
    };

    const getAccountIcon = (type: AccountType): React.JSX.Element => {
        switch (type) {
            case AccountType.Checking:
                return <Landmark className="w-3.5 h-3.5" />;
            case AccountType.Savings:
                return <Banknote className="w-3.5 h-3.5" />;
            case AccountType.Credit:
                return <CreditCard className="w-3.5 h-3.5" />;
            case AccountType.Cash:
                return <Wallet className="w-3.5 h-3.5" />;
            default:
                return <Landmark className="w-3.5 h-3.5" />;
        }
    };

    return (
        <>
            <input
                type="file"
                ref={fileInputRef}
                onChange={handleFileChange}
                accept=".qif"
                className="hidden"
            />

            {/* Account Sidebar */}
            <aside className="w-64 flex flex-col gap-4 flex-none overflow-hidden pr-2">
                <Card className="bg-card border-border rounded-sm h-full flex flex-col overflow-hidden">
                    <div className="px-4 py-3 flex justify-between items-center border-b border-border bg-muted/30">
                        <h2 className="text-xs text-muted-foreground font-bold uppercase tracking-widest">
                            Accounts
                        </h2>
                        <Link
                            href="/accounts"
                            className="text-primary hover:text-white transition-colors"
                        >
                            <Plus className="w-3 h-3" />
                        </Link>
                    </div>
                    <ScrollArea className="flex-1">
                        <div className="p-2 space-y-1">
                            {accounts.map(
                                (acc: IAccount): React.JSX.Element => (
                                    <ContextMenu key={acc.id}>
                                        <ContextMenuTrigger>
                                            <div
                                                onClick={(): void => setActiveAccountId(acc.id)}
                                                className={cn(
                                                    'p-2 rounded-sm cursor-pointer transition-all border',
                                                    activeAccountId === acc.id
                                                        ? 'bg-primary/10 border-primary/30'
                                                        : 'bg-transparent border-transparent hover:bg-accent/50',
                                                )}
                                            >
                                                <div className="flex justify-between items-start mb-1">
                                                    <span
                                                        className={cn(
                                                            'text-sm font-bold',
                                                            activeAccountId === acc.id
                                                                ? 'text-primary'
                                                                : 'text-foreground',
                                                        )}
                                                    >
                                                        {acc.name}
                                                    </span>
                                                    <span className="text-[10px] text-muted-foreground opacity-50">
                                                        {getAccountIcon(acc.type)}
                                                    </span>
                                                </div>
                                                <div className="text-sm font-mono font-bold text-muted-foreground">
                                                    {Money.formatCurrency(
                                                        transactions
                                                            .filter(
                                                                (t: ITransaction): boolean =>
                                                                    t.accountId === acc.id,
                                                            )
                                                            .reduce(
                                                                (
                                                                    s: number,
                                                                    t: ITransaction,
                                                                ): number => s + t.totalAmount,
                                                                0,
                                                            ),
                                                    )}
                                                </div>
                                            </div>
                                        </ContextMenuTrigger>
                                        <ContextMenuContent className="w-48">
                                            <ContextMenuLabel>{acc.name}</ContextMenuLabel>
                                            <ContextMenuSeparator />
                                            <ContextMenuItem onClick={() => setAccountToEdit(acc)}>
                                                Edit Account...
                                            </ContextMenuItem>
                                            <ContextMenuItem
                                                onClick={() => setActiveAccountId(acc.id)}
                                            >
                                                View Ledger
                                            </ContextMenuItem>
                                            <ContextMenuSeparator />
                                            <ContextMenuItem
                                                variant="destructive"
                                                onClick={() => setAccountToDelete(acc.id)}
                                            >
                                                Delete Account
                                            </ContextMenuItem>
                                        </ContextMenuContent>
                                    </ContextMenu>
                                ),
                            )}
                        </div>
                    </ScrollArea>
                    <div className="p-2 border-t border-border bg-muted/20">
                        <Link
                            href="/recurring"
                            className="flex items-center gap-2 p-2 rounded-sm hover:bg-primary/10 transition-colors group"
                        >
                            <Calendar className="w-3.5 h-3.5 text-muted-foreground group-hover:text-primary" />
                            <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground group-hover:text-primary">
                                Bills & Scheduled
                            </span>
                        </Link>
                    </div>
                </Card>

                <Card className="bg-card border-border rounded-sm p-3">
                    <div className="flex justify-between items-center mb-2">
                        <span className="text-[10px] font-bold uppercase text-muted-foreground tracking-wider">
                            Sync Engine
                        </span>
                        <SyncIndicator />
                    </div>
                    <div className="flex flex-col gap-1.5">
                        <div className="flex justify-between text-sm">
                            <span className="text-muted-foreground uppercase font-bold tracking-tighter">
                                Cleared
                            </span>
                            <span className="font-mono text-emerald-500 font-bold">
                                {Money.formatCurrency(clearedBalance)}
                            </span>
                        </div>
                        <div className="flex justify-between text-sm">
                            <span className="text-muted-foreground uppercase font-bold tracking-tighter">
                                Pending
                            </span>
                            <span className="font-mono text-amber-500 font-bold">
                                {Money.formatCurrency(pendingBalance)}
                            </span>
                        </div>
                    </div>
                </Card>
            </aside>

            {/* Main Ledger Area */}
            <div className="flex-1 flex flex-col gap-4 overflow-hidden">
                <Card className="bg-card border-border rounded-sm p-3 shadow-lg flex-none relative z-10">
                    <form onSubmit={handleQuickAdd} className="grid grid-cols-12 gap-3 items-end">
                        <div className="col-span-2">
                            <label className="text-[10px] font-bold text-muted-foreground uppercase block mb-1">
                                Date
                            </label>
                            <Input
                                type="date"
                                value={entryDate}
                                onChange={(e: React.ChangeEvent<HTMLInputElement>): void =>
                                    setEntryDate(e.target.value)
                                }
                                className="h-7 text-xs font-mono uppercase px-2"
                            />
                        </div>
                        <div className="col-span-3">
                            <label className="text-[10px] font-bold text-muted-foreground uppercase block mb-1">
                                Payee / Recipient
                            </label>
                            <div className="relative">
                                <Search className="absolute left-2 top-1.5 w-3 h-3 text-muted-foreground" />
                                <Input
                                    type="text"
                                    placeholder="Who did you pay?"
                                    value={entryPayee}
                                    onChange={(e: React.ChangeEvent<HTMLInputElement>): void =>
                                        setEntryPayee(e.target.value)
                                    }
                                    className="h-7 pl-7 text-sm"
                                />
                            </div>
                        </div>
                        <div className="col-span-2">
                            <label className="text-[10px] font-bold text-muted-foreground uppercase block mb-1">
                                Amount
                            </label>
                            <Input
                                type="number"
                                step="0.01"
                                placeholder="0.00"
                                value={entryAmount}
                                onChange={(e: React.ChangeEvent<HTMLInputElement>): void =>
                                    setEntryAmount(e.target.value)
                                }
                                className="h-7 text-sm font-mono text-emerald-500 px-2"
                            />
                        </div>
                        <div className="col-span-3">
                            <label className="text-[10px] font-bold text-muted-foreground uppercase block mb-1">
                                Memo / Description
                            </label>
                            <Input
                                type="text"
                                placeholder="What was it for?"
                                value={entryMemo}
                                onChange={(e: React.ChangeEvent<HTMLInputElement>): void =>
                                    setEntryMemo(e.target.value)
                                }
                                className="h-7 text-sm px-2"
                            />
                        </div>
                        <div className="col-span-2 flex gap-2">
                            <Button
                                type="submit"
                                className="flex-1 text-xs font-black uppercase h-7"
                            >
                                Record
                            </Button>
                            <Button
                                type="button"
                                variant="outline"
                                onClick={(): void => setIsSplitDialogOpen(true)}
                                className={cn(
                                    'px-2 text-xs uppercase font-bold h-7',
                                    manualSplits.length > 0 &&
                                        'border-primary text-primary bg-primary/10',
                                )}
                            >
                                {manualSplits.length > 0
                                    ? `${manualSplits.length} Splits`
                                    : 'Split'}
                            </Button>
                        </div>
                    </form>
                </Card>

                <div className="flex items-center justify-between flex-none px-1">
                    <div className="flex gap-2">
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={handleImportClick}
                            disabled={isImporting}
                            className="h-7 text-xs font-black uppercase bg-primary/10 border-primary/20 text-primary hover:bg-primary/20"
                        >
                            {isImporting ? 'Processing QIF...' : 'Import Data'}
                        </Button>
                        <Button
                            variant="outline"
                            size="sm"
                            className="h-7 text-xs font-black uppercase"
                        >
                            Reconcile
                        </Button>
                    </div>
                </div>

                <Card className="flex-1 min-h-0 relative border-border rounded-sm overflow-hidden flex flex-col group">
                    {isImporting && (
                        <div className="absolute inset-0 bg-background/80 z-20 flex items-center justify-center backdrop-blur-sm">
                            <div className="flex flex-col items-center gap-3">
                                <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"></div>
                                <p className="text-sm font-bold text-primary uppercase tracking-[0.2em]">
                                    Processing Ledger Data...
                                </p>
                            </div>
                        </div>
                    )}
                    <TransactionTable data={filteredTransactions} />
                </Card>
            </div>

            <SplitEntryDialog
                isOpen={isSplitDialogOpen}
                onClose={(): void => setIsSplitDialogOpen(false)}
                totalAmount={Money.dollarsToCents(parseFloat(entryAmount) || 0)}
                initialSplits={manualSplits}
                onSave={handleSplitSave}
            />

            <Dialog open={!!accountToDelete} onOpenChange={() => setAccountToDelete(null)}>
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle className="uppercase font-black tracking-widest text-destructive">
                            Confirm Account Deletion
                        </DialogTitle>
                        <DialogDescription className="text-xs uppercase font-bold text-muted-foreground">
                            Are you sure you want to delete this account? Transactions will be
                            retained for reporting, but the account will be hidden from the sidebar.
                        </DialogDescription>
                    </DialogHeader>
                    <DialogFooter>
                        <Button
                            variant="outline"
                            onClick={() => setAccountToDelete(null)}
                            className="text-xs font-bold uppercase"
                        >
                            Cancel
                        </Button>
                        <Button
                            variant="destructive"
                            onClick={async () => {
                                if (accountToDelete) {
                                    await softDeleteAccount(accountToDelete);
                                    setAccountToDelete(null);
                                }
                            }}
                            className="text-xs font-bold uppercase"
                        >
                            Delete Account
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            <Dialog open={!!accountToEdit} onOpenChange={() => setAccountToEdit(null)}>
                <DialogContent className="sm:max-w-[425px] md:max-w-[600px] border-border bg-card">
                    <DialogHeader>
                        <DialogTitle className="uppercase font-black tracking-widest text-primary">
                            Edit Account Details
                        </DialogTitle>
                        <DialogDescription className="text-[10px] uppercase font-bold text-muted-foreground tracking-widest opacity-50">
                            Full historical adjustment and metadata configuration
                        </DialogDescription>
                    </DialogHeader>
                    {accountToEdit && (
                        <AccountEditForm
                            account={accountToEdit}
                            onCancel={() => setAccountToEdit(null)}
                            onSubmit={async (updated: IAccount): Promise<void> => {
                                await updateAccount(updated);
                                setAccountToEdit(null);
                            }}
                        />
                    )}
                </DialogContent>
            </Dialog>

            <ReconciliationDialog
                isOpen={isReconciliationOpen}
                onClose={() => setIsReconciliationOpen(false)}
                matches={reconciliationMatches}
                onConfirm={handleReconciliationConfirm}
            />
        </>
    );
}
