// apps/web/src/components/dashboard/ProjectionChart.tsx
'use client';

import * as React from 'react';
import { useMemo } from 'react';
import { type IProjectionDataPoint, Money } from '@path-logic/core';
import { cn } from '@/lib/utils';

interface IProjectionChartProps {
    data: Array<IProjectionDataPoint>;
    height?: number;
    className?: string;
}

export function ProjectionChart({ data, height = 200, className }: IProjectionChartProps): React.JSX.Element {

    const points = useMemo(() => {
        if (!data.length) return [];

        const min = Math.min(...data.map((d: IProjectionDataPoint) => d.projectedBalance));
        const max = Math.max(...data.map((d: IProjectionDataPoint) => d.projectedBalance));
        const range = max - min || 1;

        return data.map((d: IProjectionDataPoint, i: number) => ({
            x: (i / (data.length - 1)) * 100,
            y: 100 - ((d.projectedBalance - min) / range) * 100,
            balance: d.projectedBalance,
            date: d.date
        }));
    }, [data]);

    const pathData = useMemo(() => {
        if (points.length < 2) return "";
        return points.reduce((path: string, p: { x: number; y: number }, i: number) =>
            i === 0 ? `M ${p.x} ${p.y}` : `${path} L ${p.x} ${p.y}`, "");
    }, [points]);

    const areaPath = useMemo(() => {
        if (points.length < 2) return '';
        return `${pathData} L 100 100 L 0 100 Z`;
    }, [pathData, points]);

    if (!data.length) {
        return (
            <div className={cn("flex items-center justify-center bg-muted/10 rounded-sm border border-dashed border-border", className)} style={{ height }}>
                <p className="text-[10px] font-bold uppercase text-muted-foreground opacity-50">No projection data available</p>
            </div>
        );
    }

    const currentBalance = data[0]?.projectedBalance || 0;
    const finalBalance = data[data.length - 1]?.projectedBalance || 0;
    const isUp = finalBalance >= currentBalance;

    return (
        <div className={cn("relative group", className)}>
            <div className="flex justify-between items-end mb-4 px-1">
                <div>
                    <h3 className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest mb-1">90-Day Forecast</h3>
                    <div className="flex items-baseline gap-2">
                        <span className="text-2xl font-mono font-black tracking-tighter">
                            {Money.formatCurrency(finalBalance)}
                        </span>
                        <span className={cn(
                            "text-[10px] font-bold px-1.5 py-0.5 rounded-sm uppercase tracking-tighter",
                            isUp ? "bg-emerald-500/10 text-emerald-500" : "bg-destructive/10 text-destructive"
                        )}>
                            {isUp ? '↑' : '↓'} {Money.formatCurrency(Math.abs(finalBalance - currentBalance))}
                        </span>
                    </div>
                </div>
                <div className="text-right">
                    <p className="text-[8px] font-bold text-muted-foreground uppercase tracking-tighter">Projected Change</p>
                    <p className="text-[10px] font-mono font-bold text-muted-foreground italic">
                        By {new Date(data[data.length - 1]!.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
                    </p>
                </div>
            </div>

            <div className="relative overflow-visible" style={{ height }}>
                <svg
                    viewBox="0 0 100 100"
                    preserveAspectRatio="none"
                    className="w-full h-full overflow-visible"
                >
                    <defs>
                        <linearGradient id="chartGradient" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="0%" stopColor={isUp ? "rgb(16, 185, 129)" : "rgb(239, 68, 68)"} stopOpacity="0.2" />
                            <stop offset="100%" stopColor={isUp ? "rgb(16, 185, 129)" : "rgb(239, 68, 68)"} stopOpacity="0" />
                        </linearGradient>
                    </defs>

                    {/* Grid lines */}
                    <line x1="0" y1="25" x2="100" y2="25" stroke="currentColor" className="text-border/30" strokeWidth="0.1" strokeDasharray="1,1" />
                    <line x1="0" y1="50" x2="100" y2="50" stroke="currentColor" className="text-border/30" strokeWidth="0.1" strokeDasharray="1,1" />
                    <line x1="0" y1="75" x2="100" y2="75" stroke="currentColor" className="text-border/30" strokeWidth="0.1" strokeDasharray="1,1" />

                    {/* Area */}
                    <path
                        d={areaPath}
                        fill="url(#chartGradient)"
                    />

                    {/* Line */}
                    <path
                        d={pathData}
                        fill="none"
                        stroke={isUp ? "rgb(16, 185, 129)" : "rgb(239, 68, 68)"}
                        strokeWidth="1.5"
                        strokeLinejoin="round"
                        strokeLinecap="round"
                        className="drop-shadow-[0_0_8px_rgba(16,185,129,0.3)]"
                    />
                </svg>

                {/* Axes Labels */}
                <div className="absolute top-0 left-0 w-full h-full pointer-events-none font-bold uppercase">
                    <div className="absolute top-0 left-0 text-[8px] text-muted-foreground/50 tracking-tighter">Forecast</div>
                    <div className="absolute bottom-0 left-0 text-[8px] text-muted-foreground/50 tracking-tighter">Current</div>
                </div>
            </div>

            {/* Timeline ticks */}
            <div className="flex justify-between mt-2 px-1">
                <span className="text-[8px] font-bold text-muted-foreground/40 uppercase">Today</span>
                <span className="text-[8px] font-bold text-muted-foreground/40 uppercase">30d</span>
                <span className="text-[8px] font-bold text-muted-foreground/40 uppercase">60d</span>
                <span className="text-[8px] font-bold text-muted-foreground/40 uppercase">90d</span>
            </div>
        </div>
    );
}

// apps/web/src/app/components/dashboard/projection-chart/projection-chart.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { type IProjectionDataPoint, Money } from '@path-logic/core';

/**
 * Interface for internal coordinate mapping.
 */
interface IChartPoint {
    x: number;
    y: number;
    balance: number;
    date: string;
}

/**
 * Premium SVG-based cashflow projection chart.
 * Ported from React Sim-X visualization. Uses Angular signals for reactive rendering.
 */
@Component({
    selector: 'app-projection-chart',
    standalone: true,
    imports: [],
    templateUrl: './projection-chart.component.html',
    styleUrl: './projection-chart.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProjectionChartComponent {
    /**
     * 90-day projection data points.
     */
    readonly data = input<Array<IProjectionDataPoint>>(new Array<IProjectionDataPoint>());

    /**
     * Component height in pixels.
     * @default 200
     */
    readonly height = input<number>(200);

    /**
     * Additional CSS classes for the container.
     */
    readonly className = input<string>('');

    /**
     * Maps data points to 0-100 normalized SVG coordinates.
     */
    readonly points = computed((): Array<IChartPoint> => {
        const dataArr: Array<IProjectionDataPoint> = this.data();
        if (dataArr.length === 0) return new Array<IChartPoint>();

        const balances: Array<number> = dataArr.map(
            (d: IProjectionDataPoint): number => d.projectedBalance,
        );
        const min: number = Math.min(...balances);
        const max: number = Math.max(...balances);
        const range: number = max - min || 1;

        return dataArr.map(
            (d: IProjectionDataPoint, i: number): IChartPoint =>
                ({
                    x: (i / (dataArr.length - 1)) * 100,
                    y: 100 - ((d.projectedBalance - min) / range) * 100,
                    balance: d.projectedBalance,
                    date: d.date,
                }) satisfies IChartPoint,
        );
    });

    /**
     * Generates the SVG path 'd' attribute for the line.
     */
    readonly pathData = computed((): string => {
        const pts: Array<IChartPoint> = this.points();
        if (pts.length < 2) return '';
        return pts.reduce(
            (path: string, p: IChartPoint, i: number): string =>
                i === 0 ? `M ${p.x} ${p.y}` : `${path} L ${p.x} ${p.y}`,
            '',
        );
    });

    /**
     * Generates the SVG path 'd' attribute for the filled area.
     */
    readonly areaPath = computed((): string => {
        const pts: Array<IChartPoint> = this.points();
        if (pts.length < 2) return '';
        return `${this.pathData()} L 100 100 L 0 100 Z`;
    });

    /**
     * Whether the forecast ends higher than it starts.
     */
    readonly isUp = computed((): boolean => {
        const dataArr: Array<IProjectionDataPoint> = this.data();
        if (dataArr.length < 2) return true;
        const start: number = dataArr[0]?.projectedBalance ?? 0;
        const end: number = dataArr[dataArr.length - 1]?.projectedBalance ?? 0;
        return end >= start;
    });

    /**
     * Formatted final projected balance.
     */
    readonly formattedFinalBalance = computed((): string => {
        const dataArr: Array<IProjectionDataPoint> = this.data();
        const end: number = dataArr[dataArr.length - 1]?.projectedBalance ?? 0;
        return Money.formatCurrency(end);
    });

    /**
     * Formatted delta between start and end.
     */
    readonly formattedDelta = computed((): string => {
        const dataArr: Array<IProjectionDataPoint> = this.data();
        if (dataArr.length < 2) return '$0.00';
        const start: number = dataArr[0]?.projectedBalance ?? 0;
        const end: number = dataArr[dataArr.length - 1]?.projectedBalance ?? 0;
        return Money.formatCurrency(Math.abs(end - start));
    });

    /**
     * Formatted end date of the projection.
     */
    readonly formattedEndDate = computed((): string => {
        const dataArr: Array<IProjectionDataPoint> = this.data();
        if (dataArr.length === 0) return '';
        const end: IProjectionDataPoint | undefined = dataArr[dataArr.length - 1];
        if (!end) return '';
        return new Date(end.date).toLocaleDateString(undefined, {
            month: 'short',
            day: 'numeric',
        });
    });
}

<div [class]="'relative group ' + className()">
    @if (data().length === 0) {
        <div
            class="flex items-center justify-center bg-muted/10 rounded-sm border border-dashed border-border"
            [style.height.px]="height()"
        >
            <p class="text-[10px] font-bold uppercase text-foreground">
                No projection data available
            </p>
        </div>
    } @else {
        <div class="flex justify-between items-end mb-4 px-1">
            <div>
                <h3 class="text-[10px] font-bold text-foreground uppercase tracking-widest mb-1">
                    90-Day Forecast
                </h3>
                <div class="flex items-baseline gap-2">
                    <span class="text-2xl font-mono font-black tracking-tighter">
                        {{ formattedFinalBalance() }}
                    </span>
                    <span
                        class="text-[10px] font-bold px-1.5 py-0.5 rounded-sm uppercase tracking-tighter"
                        [class]="{
                            'bg-emerald-500/10 text-emerald-900': isUp(),
                            'bg-destructive/10 text-destructive': !isUp(),
                        }"
                    >
                        {{ isUp() ? '↑' : '↓' }}
                        {{ formattedDelta() }}
                    </span>
                </div>
            </div>
            <div class="text-right">
                <p class="text-[8px] font-bold text-foreground uppercase tracking-tighter">
                    Projected Change
                </p>
                <p class="text-[10px] font-mono font-bold text-foreground/90 italic">
                    By {{ formattedEndDate() }}
                </p>
            </div>
        </div>

        <div class="relative overflow-visible" [style.height.px]="height()">
            <svg
                viewBox="0 0 100 100"
                #chartSvg
                class="w-full h-full overflow-visible"
                role="img"
                aria-label="Daily cashflow projection chart showing forecasted balance over the next 90 days"
            >
                <title>Cashflow Projection Chart</title>
                <defs>
                    <linearGradient id="chartGradient" x1="0" y1="0" x2="0" y2="1">
                        <stop
                            offset="0%"
                            [attr.stop-color]="isUp() ? 'rgb(16, 185, 129)' : 'rgb(239, 68, 68)'"
                            stop-opacity="0.2"
                        />
                        <stop
                            offset="100%"
                            [attr.stop-color]="isUp() ? 'rgb(16, 185, 129)' : 'rgb(239, 68, 68)'"
                            stop-opacity="0"
                        />
                    </linearGradient>
                </defs>

                <!-- Grid lines (decorative) -->
                <line
                    x1="0"
                    y1="25"
                    x2="100"
                    y2="25"
                    stroke="currentColor"
                    class="text-border/30"
                    stroke-width="0.1"
                    stroke-dasharray="1,1"
                    aria-hidden="true"
                />
                <line
                    x1="0"
                    y1="50"
                    x2="100"
                    y2="50"
                    stroke="currentColor"
                    class="text-border/30"
                    stroke-width="0.1"
                    stroke-dasharray="1,1"
                    aria-hidden="true"
                />
                <line
                    x1="0"
                    y1="75"
                    x2="100"
                    y2="75"
                    stroke="currentColor"
                    class="text-border/30"
                    stroke-width="0.1"
                    stroke-dasharray="1,1"
                    aria-hidden="true"
                />

                <!-- Area -->
                <path [attr.d]="areaPath()" fill="url(#chartGradient)" aria-hidden="true" />

                <!-- Line -->
                <path
                    [attr.d]="pathData()"
                    fill="none"
                    [attr.stroke]="isUp() ? 'rgb(16, 185, 129)' : 'rgb(239, 68, 68)'"
                    stroke-width="1.5"
                    stroke-linejoin="round"
                    stroke-linecap="round"
                    [class]="{ 'drop-shadow-emerald': isUp(), 'drop-shadow-red': !isUp() }"
                    aria-hidden="true"
                />
            </svg>

            <!-- Axes Labels -->
            <div
                class="absolute top-0 left-0 w-full h-full pointer-events-none font-bold uppercase"
            >
                <div class="absolute top-0 left-0 text-[8px] text-foreground tracking-tighter">
                    Forecast
                </div>
                <div class="absolute bottom-0 left-0 text-[8px] text-foreground tracking-tighter">
                    Current
                </div>
            </div>
        </div>

        <!-- Timeline ticks -->
        <div class="flex justify-between mt-2 px-1">
            <span class="text-[8px] font-bold text-foreground/80 uppercase"> Today </span>
            <span class="text-[8px] font-bold text-foreground/80 uppercase">30d</span>
            <span class="text-[8px] font-bold text-foreground/80 uppercase">60d</span>
            <span class="text-[8px] font-bold text-foreground/80 uppercase">90d</span>
        </div>
    }
</div>
