// apps/web/src/components/ledger/TransactionTable.tsx
'use client';

import * as React from 'react';
import {
    ColumnDef,
    ColumnFiltersState,
    flexRender,
    getCoreRowModel,
    getFilteredRowModel,
    getSortedRowModel,
    Row,
    SortingState,
    VisibilityState,
    useReactTable,
} from '@tanstack/react-table';
import { useVirtualizer } from '@tanstack/react-virtual';
import { ArrowUpDown, AlertCircle, CheckCircle2, Clock } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { type ITransaction, Money, TransactionStatus, KnownCategory } from '@path-logic/core';
import { cn } from '@/lib/utils';

export const columns: Array<ColumnDef<ITransaction>> = [
    {
        accessorKey: 'date',
        header: (): React.JSX.Element => <div className="text-[10px] font-bold uppercase text-nowrap">Date</div>,
        cell: ({ row }): React.JSX.Element => <div className="font-mono text-[10px] text-muted-foreground text-nowrap">{row.getValue('date')}</div>,
    },
    {
        accessorKey: 'payee',
        header: (): React.JSX.Element => <div className="text-[10px] font-bold uppercase text-nowrap">Payee / Memo</div>,
        cell: ({ row }): React.JSX.Element => {
            const tx = row.original;
            return (
                <div className="flex flex-col">
                    <span className="font-semibold text-primary group-hover:text-foreground text-[11px] truncate max-w-[300px]">
                        {tx.payee}
                    </span>
                    <span className="text-[9px] text-muted-foreground truncate max-w-[300px]">
                        {tx.splits.length > 0
                            ? `${tx.splits.length} Splits: ${tx.splits[0]?.memo}`
                            : tx.memo}
                    </span>
                </div>
            );
        },
    },
    {
        id: 'category',
        header: (): React.JSX.Element => <div className="text-[10px] font-bold uppercase">Category</div>,
        cell: ({ row }): React.JSX.Element => {
            const tx = row.original;
            return (
                <div className="flex items-center">
                    <span className="text-[9px] bg-accent px-1.5 py-0.5 rounded-sm border border-border text-muted-foreground whitespace-nowrap uppercase tracking-tighter font-bold">
                        {tx.splits.length > 1
                            ? 'SPLIT'
                            : (tx.splits[0]?.categoryId ?? KnownCategory.Uncategorized)}
                    </span>
                </div>
            );
        },
    },
    {
        accessorKey: 'status',
        header: (): React.JSX.Element => <div className="text-[10px] font-bold uppercase text-nowrap">Status</div>,
        cell: ({ row }): React.JSX.Element => {
            const status = row.original.status;
            return (
                <div
                    className={cn(
                        "text-[9px] font-bold uppercase text-nowrap flex items-center gap-1.5",
                        status === TransactionStatus.Cleared ? "text-emerald-500" :
                            status === TransactionStatus.Pending ? "text-amber-500" : "text-primary"
                    )}
                >
                    {status === TransactionStatus.Cleared ? <CheckCircle2 className="w-3 h-3" /> : <Clock className="w-3 h-3" />}
                    {status}
                </div>
            );
        },
    },
    {
        accessorKey: 'totalAmount',
        header: (): React.JSX.Element => <div className="text-[10px] font-bold uppercase text-nowrap">Amount</div>,
        cell: ({ row }): React.JSX.Element => {
            const amount = parseFloat(row.getValue('totalAmount'));
            const formatted = Money.formatCurrency(amount);

            return (
                <div className={cn(
                    "text-right font-mono font-bold text-[11px] text-nowrap",
                    amount < 0 ? "text-destructive" : "text-emerald-500"
                )}>
                    {formatted}
                </div>
            );
        },
    },
    {
        id: 'balance',
        header: (): React.JSX.Element => <div className="text-[10px] font-bold uppercase text-nowrap">Balance</div>,
        cell: ({ row }): React.JSX.Element => {
            const balance = (row.original as ITransaction & { runningBalance?: number }).runningBalance ?? 0;
            const formatted = Money.formatCurrency(balance);

            return (
                <div className={cn(
                    "text-right font-mono font-bold text-[11px] text-nowrap",
                    balance < 0 ? "text-destructive" : "text-emerald-500"
                )}>
                    {formatted}
                </div>
            );
        },
    },
];

interface ITransactionTableProps {
    data: Array<ITransaction>;
}

interface IMemoizedLedgerRowProps {
    row: Row<ITransaction>;
    virtualRow: {
        key: React.Key;
        index: number;
        start: number;
    };
    isActive: boolean;
    setActiveIndex: (index: number) => void;
}

const MemoizedLedgerRow = React.memo(({
    row,
    virtualRow,
    isActive,
    setActiveIndex
}: IMemoizedLedgerRowProps) => {
    return (
        <div
            key={virtualRow.key}
            data-state={row.getIsSelected() && 'selected'}
            className={cn(
                "flex items-center hover:bg-accent/50 border-none group cursor-pointer h-9 transition-colors absolute w-full",
                isActive && "bg-accent/80 outline outline-1 outline-primary z-10"
            )}
            style={{
                top: 0,
                transform: `translateY(${virtualRow.start}px)`,
            }}
            onClick={(): void => setActiveIndex(virtualRow.index)}
        >
            {row.getVisibleCells().map((cell) => {
                const widthMap: Record<string, string> = {
                    'date': 'w-[100px]',
                    'payee': 'flex-1 min-w-[300px]',
                    'category': 'w-[140px]',
                    'status': 'w-[120px]',
                    'totalAmount': 'w-[120px]',
                    'balance': 'w-[120px]'
                };
                const widthClass = widthMap[cell.column.id] || 'w-[100px]';

                return (
                    <div
                        key={cell.id}
                        className={cn("px-3 h-9 flex items-center overflow-hidden", widthClass)}
                    >
                        {flexRender(
                            cell.column.columnDef.cell,
                            cell.getContext()
                        )}
                    </div>
                );
            })}
        </div>
    );
}, (prev, next) => {
    return prev.isActive === next.isActive &&
        prev.virtualRow.index === next.virtualRow.index &&
        prev.virtualRow.start === next.virtualRow.start &&
        prev.row.id === next.row.id &&
        prev.row.getIsSelected() === next.row.getIsSelected();
});
MemoizedLedgerRow.displayName = 'MemoizedLedgerRow';

export function TransactionTable({ data }: ITransactionTableProps): React.JSX.Element {
    const [sorting, setSorting] = React.useState<SortingState>([]);
    const [columnFilters, setColumnFilters] = React.useState<ColumnFiltersState>([]);
    const [columnVisibility, setColumnVisibility] = React.useState<VisibilityState>({});
    const [rowSelection, setRowSelection] = React.useState({});
    const [activeIndex, setActiveIndex] = React.useState(0);
    const [monthsToShow, setMonthsToShow] = React.useState(6);
    const [isAtTop, setIsAtTop] = React.useState(true);
    const parentRef = React.useRef<HTMLDivElement>(null);
    const lastKeyTime = React.useRef<number>(0);

    // Sort and calculate running balances for the ENTIRE dataset
    const sortedDataWithBalances = React.useMemo(() => {
        // 1. Sort by date (ASC), then by type priority (income first)
        const sorted = [...data].sort((a, b) => {
            // Primary: Date comparison
            if (a.date !== b.date) {
                return a.date.localeCompare(b.date);
            }
            // Secondary: Income (positive) before expenses (negative)
            const aPriority = a.totalAmount >= 0 ? 0 : 1;
            const bPriority = b.totalAmount >= 0 ? 0 : 1;
            return aPriority - bPriority;
        });

        // 2. Calculate cumulative running balance
        let runningBalance = 0;
        return sorted.map((tx) => {
            runningBalance += tx.totalAmount;
            return { ...tx, runningBalance };
        });
    }, [data]);

    // Filter data centered on current date
    const windowedData = React.useMemo(() => {
        const today = new Date();
        const pastCutoff = new Date(today);
        pastCutoff.setMonth(pastCutoff.getMonth() - monthsToShow);
        const futureCutoff = new Date(today);
        futureCutoff.setMonth(futureCutoff.getMonth() + 3); // Show 3 months into future

        return sortedDataWithBalances.filter((tx) => {
            const txDate = new Date(tx.date);
            return txDate >= pastCutoff && txDate <= futureCutoff;
        });
    }, [sortedDataWithBalances, monthsToShow]);

    const table = useReactTable({
        data: windowedData,
        columns,
        onSortingChange: setSorting,
        onColumnFiltersChange: setColumnFilters,
        getCoreRowModel: getCoreRowModel(),
        getSortedRowModel: getSortedRowModel(),
        getFilteredRowModel: getFilteredRowModel(),
        onColumnVisibilityChange: setColumnVisibility,
        onRowSelectionChange: setRowSelection,
        state: {
            sorting,
            columnFilters,
            columnVisibility,
            rowSelection,
        },
    });

    const { rows } = table.getRowModel();

    // Virtualization setup
    const virtualizer = useVirtualizer({
        count: rows.length,
        getScrollElement: () => parentRef.current,
        estimateSize: () => 36, // h-9
        overscan: 20, // Balanced for smoothness vs render cost
    });

    // Keyboard navigation
    const handleKeyDown = (e: React.KeyboardEvent): void => {
        if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
            e.preventDefault();

            // Throttle state updates to roughly 60fps (16ms)
            const now = performance.now();
            if (now - lastKeyTime.current < 16) return;
            lastKeyTime.current = now;

            if (rows.length === 0) return;

            const nextIndex = e.key === 'ArrowDown'
                ? Math.min(activeIndex + 1, rows.length - 1)
                : Math.max(activeIndex - 1, 0);

            if (nextIndex !== activeIndex) {
                setActiveIndex(nextIndex);
                virtualizer.scrollToIndex(nextIndex, { align: 'auto', behavior: 'auto' });
            }
        } else if (e.key === 'Enter') {
            e.preventDefault();
            const activeRow = rows[activeIndex];
            if (activeRow) {
                console.log('Editing transaction:', activeRow.original);
            }
        }
    };

    // Safety: Clamp activeIndex when data or filters change the row count
    React.useEffect((): void => {
        if (rows.length > 0 && activeIndex >= rows.length) {
            setActiveIndex(rows.length - 1);
        } else if (rows.length === 0 && activeIndex !== 0) {
            setActiveIndex(0);
        }
    }, [rows.length]);

    // Track scroll position to show/hide Load Older History button
    React.useEffect(() => {
        const scrollElement = parentRef.current;
        if (!scrollElement) return;

        const handleScroll = (): void => {
            const scrollTop = scrollElement.scrollTop;
            setIsAtTop(scrollTop < 50); // Show button when within 50px of top
        };

        scrollElement.addEventListener('scroll', handleScroll);
        return () => scrollElement.removeEventListener('scroll', handleScroll);
    }, []);

    // Scroll to current date or newest transaction on initial load
    React.useEffect(() => {
        if (rows.length === 0) return;

        const today = new Date();
        today.setHours(0, 0, 0, 0);

        // Find the index of today's date or the closest future date
        let targetIndex = rows.findIndex((row) => {
            const rowDate = new Date(row.original.date);
            rowDate.setHours(0, 0, 0, 0);
            return rowDate >= today;
        });

        // If no future dates found, scroll to the last (newest) transaction
        if (targetIndex === -1) {
            targetIndex = rows.length - 1;
        }

        // Scroll to the target index
        virtualizer.scrollToIndex(targetIndex, { align: 'center', behavior: 'auto' });
        setActiveIndex(targetIndex);
    }, [rows.length, virtualizer]);

    return (
        <div className="w-full flex flex-col h-full overflow-hidden focus:outline-none" onKeyDown={handleKeyDown} tabIndex={0}>
            {/* Toolbar */}
            <div className="flex items-center py-2 px-1 justify-between flex-none bg-background">
                <Input
                    placeholder="Filter ledger (CMD+K)..."
                    value={(table.getColumn('payee')?.getFilterValue() as string) ?? ''}
                    onChange={(event): void =>
                        table.getColumn('payee')?.setFilterValue(event.target.value)
                    }
                    className="max-w-sm h-7 text-[10px] bg-background border-border uppercase tracking-wider focus-visible:ring-1 focus-visible:ring-primary"
                />
                <div className="text-[9px] font-mono text-muted-foreground uppercase px-2 translate-y-1">
                    Showing {rows.length} records • Last {monthsToShow} months
                </div>
            </div>

            <div className="flex-1 border border-border rounded-sm bg-background relative flex flex-col min-h-0 overflow-hidden">
                {/* Header - Fixed at top, independent of scroll */}
                <div className="flex-none bg-accent border-b border-border z-20">
                    {table.getHeaderGroups().map((headerGroup) => (
                        <div key={headerGroup.id} className="flex h-8 px-1 items-center">
                            {headerGroup.headers.map((header) => {
                                // Define explicit widths or flex basis for alignment
                                const widthMap: Record<string, string> = {
                                    'date': 'w-[100px]',
                                    'payee': 'flex-1 min-w-[300px]',
                                    'category': 'w-[140px]',
                                    'status': 'w-[120px]',
                                    'totalAmount': 'w-[120px]',
                                    'balance': 'w-[120px]'
                                };
                                const widthClass = widthMap[header.id] || 'w-[100px]';

                                return (
                                    <div
                                        key={header.id}
                                        className={cn(
                                            "px-3 text-muted-foreground font-bold text-[10px] uppercase",
                                            widthClass
                                        )}
                                    >
                                        {header.isPlaceholder
                                            ? null
                                            : flexRender(
                                                header.column.columnDef.header,
                                                header.getContext()
                                            )}
                                    </div>
                                );
                            })}
                        </div>
                    ))}
                </div>

                {/* Body - Scrollable Virtual Area */}
                <div
                    ref={parentRef}
                    className="flex-1 overflow-auto ledger-scroll"
                >
                    {/* Load Older History - Now at the top */}
                    {windowedData.length < data.length && rows.length > 0 && isAtTop && (
                        <div className="px-3 border-b border-border bg-background sticky top-0 z-10">
                            <button
                                onClick={(): void => setMonthsToShow(prev => prev + 6)}
                                className="w-full py-4 text-[9px] font-bold text-primary hover:text-primary hover:bg-primary/5 uppercase tracking-[0.2em] transition-colors"
                            >
                                ↑ Load older history (currently showing {monthsToShow} months) ↑
                            </button>
                        </div>
                    )}

                    <div style={{ height: `${virtualizer.getTotalSize()}px`, width: '100%', position: 'relative' }}>
                        {virtualizer.getVirtualItems().map((virtualRow) => {
                            const row = rows[virtualRow.index];
                            if (!row) return null;

                            return (
                                <MemoizedLedgerRow
                                    key={virtualRow.key}
                                    row={row}
                                    virtualRow={virtualRow}
                                    isActive={virtualRow.index === activeIndex}
                                    setActiveIndex={setActiveIndex}
                                />
                            );
                        })}
                    </div>

                    {rows.length === 0 && (
                        <div className="flex flex-col items-center justify-center text-muted-foreground text-[10px] uppercase tracking-widest gap-4 min-h-[300px] text-center px-8 relative z-10">
                            {data.length === 0 ? (
                                <>
                                    <div className="text-primary font-bold">Ledger is empty</div>
                                    <div>Import a QIF file or add a transaction to get started</div>
                                </>
                            ) : windowedData.length === 0 ? (
                                <>
                                    <div>No transactions in the last {monthsToShow} months</div>
                                    <button
                                        onClick={(): void => setMonthsToShow(prev => prev + 6)}
                                        className="text-primary hover:underline font-bold"
                                    >
                                        Check older history?
                                    </button>
                                </>
                            ) : (
                                <>
                                    <div>No transactions match your current filters</div>
                                    <button
                                        onClick={(): void => table.resetColumnFilters()}
                                        className="text-primary hover:underline font-bold"
                                    >
                                        Clear all filters
                                    </button>
                                </>
                            )}
                        </div>
                    )}
                </div>
            </div>

            <div className="flex items-center justify-between py-2 px-1 text-[9px] font-mono text-muted-foreground uppercase bg-background flex-none">
                <div className="flex-1">
                    Showing {windowedData.length} of {data.length} Transactions
                </div>
            </div>
        </div>
    );
}

// app/src/app/components/ledger/transaction-table/transaction-table.component.ts
import { CommonModule, DatePipe, DecimalPipe } from '@angular/common';
import type { ElementRef, OnInit } from '@angular/core';
import {
    ChangeDetectionStrategy,
    Component,
    computed,
    HostListener,
    inject,
    input,
    model,
    output,
    signal,
    viewChild
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import type { ITransaction } from '@core';
import { KnownCategory, Money, TransactionStatus } from '@core';
import type { ColumnDef, ColumnFiltersState, SortingState } from '@tanstack/angular-table';
import {
    createAngularTable,
    createColumnHelper,
    getCoreRowModel,
    getFilteredRowModel,
    getSortedRowModel
} from '@tanstack/angular-table';
import { injectVirtualizer } from '@tanstack/angular-virtual';
import { CheckCircle2, Clock, LucideAngularModule } from 'lucide-angular';

/**
 * High-density transaction table component.
 * Uses TanStack Table for logic and TanStack Virtual for performance.
 * Features keyboard navigation and context menu integration.
 */
@Component({
    selector: 'transaction-table',
    standalone: true,
    imports: [CommonModule, FormsModule, LucideAngularModule],
    templateUrl: './transaction-table.component.html',
    styleUrls: ['./transaction-table.component.css'],
    providers: [DecimalPipe, DatePipe],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class TransactionTableComponent implements OnInit {
    private readonly decimalPipe = inject(DecimalPipe);
    private readonly datePipe = inject(DatePipe);

    // Inputs
    readonly data = input.required<Array<ITransaction>>();
    readonly className = input<string>('');

    // Outputs
    readonly editClicked = output<ITransaction>();
    readonly deleted = output<string>();
    readonly duplicateClicked = output<ITransaction>();

    // State
    readonly sorting = signal<SortingState>(new Array<SortingState[number]>());
    readonly columnFilters = signal<ColumnFiltersState>(new Array<ColumnFiltersState[number]>());
    readonly activeIndex = model<number>(0);
    readonly monthsToShow = signal<number>(6);
    readonly isAtTop = signal<boolean>(true);

    // Template children
    readonly parentRef = viewChild<ElementRef<HTMLDivElement>>('parentRef');

    // Column Helper
    private readonly columnHelper = createColumnHelper<ITransaction>();

    // Columns Definition
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    readonly columns: Array<ColumnDef<ITransaction, any>> = new Array<ColumnDef<ITransaction, any>>(
        this.columnHelper.accessor('date', {
            header: () => 'Date',
            cell: info => info.getValue()
        }),
        this.columnHelper.accessor(
            row => ({
                payee: row.payee,
                memo:
                    row.splits.length > 1
                        ? `${row.splits.length} Splits: ${row.splits[0]?.memo ?? ''}`
                        : (row.memo ?? '')
            }),
            {
                id: 'payee',
                header: () => 'Payee / Memo',
                // Filter against the payee name string, not the composed object
                filterFn: (row, _colId, filterValue: string) =>
                    row.original.payee.toLowerCase().includes((filterValue as string).toLowerCase())
            }
        ),
        this.columnHelper.accessor(
            row =>
                row.splits.length > 1
                    ? 'SPLIT'
                    : (row.splits[0]?.categoryId ?? KnownCategory.Uncategorized),
            {
                id: 'category',
                header: () => 'Category'
            }
        ),
        this.columnHelper.accessor('status', {
            header: () => 'Status',
            cell: info => info.getValue()
        }),
        this.columnHelper.accessor('totalAmount', {
            header: () => 'Amount',
            cell: info => info.getValue()
        }),
        this.columnHelper.accessor(
            row => (row as ITransaction & { runningBalance?: number }).runningBalance ?? 0,
            {
                id: 'balance',
                header: () => 'Balance',
                cell: info => info.getValue()
            }
        )
    );

    // Computed: Sorted and Balanced Data
    readonly sortedDataWithBalances = computed(() => {
        const rawData = this.data();
        if (rawData.length === 0) return new Array<ITransaction & { runningBalance: number }>();

        // 1. Sort by date (ASC), then by type priority
        const sorted = [...rawData].sort((a, b) => {
            if (a.date !== b.date) {
                return a.date.localeCompare(b.date);
            }
            const aPriority = a.totalAmount >= 0 ? 0 : 1;
            const bPriority = b.totalAmount >= 0 ? 0 : 1;
            return aPriority - bPriority;
        });

        // 2. Calculate running balance
        let balance = 0;
        return sorted.map(tx => {
            balance += tx.totalAmount;
            return { ...tx, runningBalance: balance };
        }) as Array<ITransaction & { runningBalance: number }>;
    });

    // Computed: Windowed Data (centered on today)
    readonly windowedData = computed(() => {
        const fullData = this.sortedDataWithBalances();
        const months = this.monthsToShow();

        const today = new Date();
        const pastCutoff = new Date(today);
        pastCutoff.setMonth(pastCutoff.getMonth() - months);
        const futureCutoff = new Date(today);
        futureCutoff.setMonth(futureCutoff.getMonth() + 3);

        return fullData.filter(tx => {
            const txDate = new Date(tx.date);
            return txDate >= pastCutoff && txDate <= futureCutoff;
        });
    });

    // Table Instance
    readonly table = createAngularTable(() => ({
        data: this.windowedData(),
        columns: this.columns,
        state: {
            sorting: this.sorting(),
            columnFilters: this.columnFilters()
        },
        onSortingChange: (updaterOrValue): void => {
            if (typeof updaterOrValue === 'function') {
                this.sorting.update(updaterOrValue);
            } else {
                this.sorting.set(updaterOrValue);
            }
        },
        onColumnFiltersChange: (updaterOrValue): void => {
            if (typeof updaterOrValue === 'function') {
                this.columnFilters.update(updaterOrValue);
            } else {
                this.columnFilters.set(updaterOrValue);
            }
        },
        getCoreRowModel: getCoreRowModel(),
        getSortedRowModel: getSortedRowModel(),
        getFilteredRowModel: getFilteredRowModel()
    }));

    // Virtualization
    readonly virtualizer = injectVirtualizer(() => ({
        count: this.table.getRowModel().rows.length,
        scrollElement: this.parentRef()?.nativeElement ?? undefined,
        estimateSize: (): number => 36, // h-9
        overscan: 20
    }));

    ngOnInit(): void {
        // Initial scroll to today
        setTimeout(() => this.scrollToToday(), 100);
    }

    @HostListener('keydown', ['$event'])
    handleKeyDown(event: KeyboardEvent): void {
        const rows = this.table.getRowModel().rows;
        if (rows.length === 0) return;

        if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
            event.preventDefault();
            const current = this.activeIndex();
            const next =
                event.key === 'ArrowDown'
                    ? Math.min(current + 1, rows.length - 1)
                    : Math.max(current - 1, 0);

            if (next !== current) {
                this.activeIndex.set(next);
                this.virtualizer.scrollToIndex(next, { align: 'auto' });
            }
        } else if (event.key === 'Enter') {
            event.preventDefault();
            const activeRow = rows[this.activeIndex()];
            if (activeRow) {
                this.editClicked.emit(activeRow.original);
            }
        }
    }

    onScroll(event: Event): void {
        const element = event.target as HTMLElement;
        this.isAtTop.set(element.scrollTop < 50);
    }

    loadMoreHistory(): void {
        this.monthsToShow.update(m => m + 6);
    }

    formatCurrency(amount: number): string {
        return Money.formatCurrency(amount);
    }

    getCategoryClass(_category: string): string {
        return 'text-[9px] bg-surface-100 px-1.5 py-0.5 rounded-sm border border-surface-200 text-surface-500 whitespace-nowrap uppercase tracking-tighter font-bold';
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    getStatusIcon(status: TransactionStatus): any {
        return status === TransactionStatus.Cleared ? CheckCircle2 : Clock;
    }

    getStatusClass(status: string): string {
        if (status === TransactionStatus.Cleared) return 'text-emerald-900';
        if (status === TransactionStatus.Pending) return 'text-amber-500';
        return 'text-primary';
    }

    private scrollToToday(): void {
        const rows = this.table.getRowModel().rows;
        if (rows.length === 0) return;

        const today = new Date();
        today.setHours(0, 0, 0, 0);

        let targetIndex = rows.findIndex(row => {
            const rowDate = new Date(row.original.date);
            rowDate.setHours(0, 0, 0, 0);
            return rowDate >= today;
        });

        if (targetIndex === -1) targetIndex = rows.length - 1;

        this.virtualizer.scrollToIndex(targetIndex, { align: 'center' });
        this.activeIndex.set(targetIndex);
    }

    // Lucide icons
    readonly CheckCircle2 = CheckCircle2;
    readonly Clock = Clock;
}

<div
    class="w-full flex flex-col h-full overflow-hidden focus:outline-none"
    (keydown)="handleKeyDown($event)"
    tabindex="0"
>
    <!-- Toolbar -->
    <div class="flex items-center py-2 px-1 justify-between flex-none bg-surface-50">
        <div class="relative max-w-sm">
            <input
                type="text"
                placeholder="Filter ledger..."
                [ngModel]="table.getState().columnFilters[0]?.value ?? ''"
                (ngModelChange)="table.getColumn('payee')?.setFilterValue($event)"
                class="w-full h-7 text-[10px] bg-surface-50 border border-surface-200 rounded-md px-3 uppercase tracking-wider focus:outline-none focus:ring-1 focus:ring-primary"
            />
        </div>
        <div class="text-[9px] font-mono text-surface-500 uppercase px-2 translate-y-1">
            Showing {{ table.getRowModel().rows.length }} records • Last {{ monthsToShow() }} months
        </div>
    </div>

    <div
        class="flex-1 border border-surface-200 rounded-sm bg-surface-50 relative flex flex-col min-h-0 overflow-hidden"
    >
        <!-- Header -->
        <div class="flex-none bg-surface-100 border-b border-surface-200 z-20">
            @for (headerGroup of table.getHeaderGroups(); track headerGroup.id) {
                <div class="flex h-8 px-1 items-center">
                    @for (header of headerGroup.headers; track header.id) {
                        <div
                            class="px-3 text-surface-500 font-bold text-[10px] uppercase"
                            [class.flex-1]="header.id === 'payee'"
                            [class.min-w-[300px]]="header.id === 'payee'"
                            [class.w-[100px]]="header.id === 'date'"
                            [class.w-[140px]]="header.id === 'category'"
                            [class.w-[120px]]="
                                header.id === 'status' ||
                                header.id === 'totalAmount' ||
                                header.id === 'balance'
                            "
                        >
                            @if (!header.isPlaceholder) {
                                {{ $any(header.column.columnDef.header)(header.getContext()) }}
                            }
                        </div>
                    }
                </div>
            }
        </div>

        <!-- Body -->
        <div #parentRef class="flex-1 overflow-auto ledger-scroll" (scroll)="onScroll($event)">
            @if (
                windowedData().length < data().length &&
                table.getRowModel().rows.length > 0 &&
                isAtTop()
            ) {
                <div class="px-3 border-b border-surface-200 bg-surface-50 sticky top-0 z-10">
                    <button
                        (click)="loadMoreHistory()"
                        class="w-full py-4 text-[9px] font-bold text-primary hover:text-primary hover:bg-primary/5 uppercase tracking-[0.2em] transition-colors"
                    >
                        ↑ Load older history (currently showing {{ monthsToShow() }} months) ↑
                    </button>
                </div>
            }

            <div [style.height.px]="virtualizer.getTotalSize()" class="w-full relative">
                @for (virtualRow of virtualizer.getVirtualItems(); track virtualRow.key) {
                    @let row = table.getRowModel().rows[virtualRow.index];
                    @if (row) {
                        <div
                            class="flex items-center hover:bg-surface-100/50 border-none group cursor-pointer h-9 transition-colors absolute w-full"
                            [class]="{
                                'bg-surface-100/80 outline outline-1 outline-primary z-10':
                                    virtualRow.index === activeIndex()
                            }"
                            [style.top.px]="0"
                            [style.transform]="'translateY(' + virtualRow.start + 'px)'"
                            (click)="activeIndex.set(virtualRow.index)"
                            (keydown.enter)="activeIndex.set(virtualRow.index)"
                            (keydown.space)="activeIndex.set(virtualRow.index)"
                            tabindex="0"
                            role="button"
                        >
                            @for (cell of row.getVisibleCells(); track cell.id) {
                                <div
                                    class="px-3 h-9 flex items-center overflow-hidden"
                                    [class.flex-1]="cell.column.id === 'payee'"
                                    [class.min-w-[300px]]="cell.column.id === 'payee'"
                                    [class.w-[100px]]="cell.column.id === 'date'"
                                    [class.w-[140px]]="cell.column.id === 'category'"
                                    [class.w-[120px]]="
                                        cell.column.id === 'status' ||
                                        cell.column.id === 'totalAmount' ||
                                        cell.column.id === 'balance'
                                    "
                                >
                                    @switch (cell.column.id) {
                                        @case ('date') {
                                            <div
                                                class="font-mono text-[10px] text-surface-500 text-nowrap"
                                            >
                                                {{ cell.getValue() }}
                                            </div>
                                        }
                                        @case ('payee') {
                                            @let cellValue = $any(cell.getValue());
                                            <div class="flex flex-col">
                                                <span
                                                    class="font-semibold text-primary group-hover:text-surface-800 text-[11px] truncate max-w-[300px]"
                                                >
                                                    {{ cellValue.payee }}
                                                </span>
                                                <span
                                                    class="text-[9px] text-surface-500 truncate max-w-[300px]"
                                                >
                                                    {{ cellValue.memo }}
                                                </span>
                                            </div>
                                        }
                                        @case ('category') {
                                            <div class="flex items-center">
                                                <span
                                                    [class]="
                                                        getCategoryClass($any(cell.getValue()))
                                                    "
                                                >
                                                    {{ cell.getValue() }}
                                                </span>
                                            </div>
                                        }
                                        @case ('status') {
                                            <div
                                                class="text-[9px] font-bold uppercase text-nowrap flex items-center gap-1.5"
                                                [class]="getStatusClass($any(cell.getValue()))"
                                            >
                                                <lucide-icon
                                                    [img]="getStatusIcon($any(cell.getValue()))"
                                                    class="w-3 h-3"
                                                />
                                                {{ cell.getValue() }}
                                            </div>
                                        }
                                        @case ('totalAmount') {
                                            <div
                                                class="text-right font-mono font-bold text-[11px] text-nowrap w-full"
                                                [class.text-red-500]="$any(cell.getValue()) < 0"
                                                [class.text-emerald-900]="
                                                    $any(cell.getValue()) >= 0
                                                "
                                            >
                                                {{ formatCurrency($any(cell.getValue())) }}
                                            </div>
                                        }
                                        @case ('balance') {
                                            <div
                                                class="text-right font-mono font-bold text-[11px] text-nowrap w-full"
                                                [class.text-red-500]="$any(cell.getValue()) < 0"
                                                [class.text-emerald-900]="
                                                    $any(cell.getValue()) >= 0
                                                "
                                            >
                                                {{ formatCurrency($any(cell.getValue())) }}
                                            </div>
                                        }
                                    }
                                </div>
                            }
                        </div>
                    }
                }
            </div>

            @if (table.getRowModel().rows.length === 0) {
                <div
                    class="flex flex-col items-center justify-center text-surface-500 text-[10px] uppercase tracking-widest gap-4 min-h-[300px] text-center px-8 relative z-10"
                >
                    @if (data().length === 0) {
                        <div class="text-primary font-bold">Ledger is empty</div>
                        <div>Import a QIF file or add a transaction to get started</div>
                    } @else if (windowedData().length === 0) {
                        <div>No transactions in the last {{ monthsToShow() }} months</div>
                        <button
                            (click)="loadMoreHistory()"
                            class="text-primary hover:underline font-bold"
                        >
                            Check older history?
                        </button>
                    } @else {
                        <div>No transactions match your current filters</div>
                        <button
                            (click)="table.getColumn('payee')?.setFilterValue('')"
                            class="text-primary hover:underline font-bold"
                        >
                            Clear all filters
                        </button>
                    }
                </div>
            }
        </div>
    </div>

    <div
        class="flex items-center justify-between py-2 px-1 text-[9px] font-mono text-surface-500 uppercase bg-surface-50 flex-none"
    >
        <div class="flex-1">
            Showing {{ windowedData().length }} of {{ data().length }} Transactions
        </div>
    </div>
</div>
