// app/src/app/components/onboarding/new-account-dialog/new-account-dialog.component.ts
import {
    ChangeDetectionStrategy,
    Component,
    computed,
    effect,
    inject,
    input,
    output,
    signal
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import type { IAccount, ISODateString } from '@core';
import { AccountType, TypeGuards } from '@core';
import {
    Banknote,
    Car,
    ChevronDown,
    ChevronUp,
    CreditCard,
    Home,
    Landmark,
    LucideAngularModule,
    Receipt,
    Wallet,
    X
} from 'lucide-angular';
import { Button } from 'primeng/button';
import { Dialog } from 'primeng/dialog';
import { Step, StepList, StepPanel, StepPanels, Stepper } from 'primeng/stepper';

import { PostHogService } from '../../../services/posthog/posthog.service';
import { LoanDetailsFormComponent } from '../loan-details-form/loan-details-form.component';

/**
 * Wizard step types.
 */
type WizardStep = 'select-type' | 'enter-details' | 'creating';

/**
 * Account type option for the wizard.
 */
interface IAccountTypeOption {
    type: AccountType;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    icon: any;
    label: string;
    description: string;
}

const PRIMARY_TYPES: Array<IAccountTypeOption> = [
    {
        type: AccountType.Checking,
        icon: Landmark,
        label: 'Checking',
        description: 'Daily spending & income'
    },
    {
        type: AccountType.Savings,
        icon: Banknote,
        label: 'Savings',
        description: 'Long-term goals'
    },
    {
        type: AccountType.Credit,
        icon: CreditCard,
        label: 'Credit Card',
        description: 'Track spending & debt'
    },
    {
        type: AccountType.Cash,
        icon: Wallet,
        label: 'Cash',
        description: 'Physical currency'
    }
];

const LOAN_TYPES: Array<IAccountTypeOption> = [
    {
        type: AccountType.Mortgage,
        icon: Home,
        label: 'Mortgage',
        description: 'Home loan & equity'
    },
    {
        type: AccountType.AutoLoan,
        icon: Car,
        label: 'Auto Loan',
        description: 'Vehicle financing'
    },
    {
        type: AccountType.PersonalLoan,
        icon: Receipt,
        label: 'Personal Loan',
        description: 'Unsecured debt'
    }
];

/**
 * Styling and theming for account types.
 */
const TYPE_THEMING: Record<string, { accentBg: string; iconText: string; iconBg: string }> = {
    [AccountType.Checking]: {
        accentBg: 'bg-teal-500',
        iconText: 'text-teal-500',
        iconBg: 'bg-teal-500/10'
    },
    [AccountType.Savings]: {
        accentBg: 'bg-blue-500',
        iconText: 'text-blue-500',
        iconBg: 'bg-blue-500/10'
    },
    [AccountType.Credit]: {
        accentBg: 'bg-purple-500',
        iconText: 'text-purple-500',
        iconBg: 'bg-purple-500/10'
    },
    [AccountType.Cash]: {
        accentBg: 'bg-green-500',
        iconText: 'text-green-500',
        iconBg: 'bg-green-500/10'
    },
    [AccountType.Mortgage]: {
        accentBg: 'bg-amber-500',
        iconText: 'text-amber-500',
        iconBg: 'bg-amber-500/10'
    },
    [AccountType.AutoLoan]: {
        accentBg: 'bg-amber-500',
        iconText: 'text-amber-500',
        iconBg: 'bg-amber-500/10'
    },
    [AccountType.PersonalLoan]: {
        accentBg: 'bg-amber-500',
        iconText: 'text-amber-500',
        iconBg: 'bg-amber-500/10'
    }
};

/**
 * Dialog for creating a new account.
 * Guides the user through type selection and basic configuration.
 */
@Component({
    selector: 'new-account-dialog',
    standalone: true,
    imports: [
        FormsModule,
        LucideAngularModule,
        LoanDetailsFormComponent,
        Stepper,
        StepList,
        StepPanels,
        Step,
        StepPanel,
        Button,
        Dialog
    ],
    templateUrl: './new-account-dialog.component.html',
    styleUrls: ['./new-account-dialog.component.css'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class NewAccountDialogComponent {
    private readonly posthogService = inject(PostHogService);

    // Inputs
    readonly isOpen = input.required<boolean>();

    // Outputs
    readonly closed = output();
    readonly accountCreated = output<IAccount>();

    // State
    readonly step = signal<WizardStep>('select-type');
    readonly selectedType = signal<AccountType | null>(null);
    readonly showLoans = signal<boolean>(false);
    readonly accountName = signal<string>('');
    readonly institutionName = signal<string>('');
    readonly initialBalance = signal<string>('');
    readonly error = signal<string | null>(null);

    // Computed
    /**
     * Stepper value based on current step name.
     */
    readonly stepValue = computed(() => {
        switch (this.step()) {
            case 'select-type':
                return 1;
            case 'enter-details':
                return 2;
            case 'creating':
                return 2;
            default:
                return 1;
        }
    });

    readonly primaryTypes = signal(PRIMARY_TYPES);
    readonly loanTypes = signal(LOAN_TYPES);

    readonly selectedOption = computed(() => {
        const type = this.selectedType();
        if (!type) return null;
        return [...PRIMARY_TYPES, ...LOAN_TYPES].find(opt => opt.type === type) || null;
    });

    readonly theming = computed(() => {
        const type = this.selectedType();
        if (!type || !TYPE_THEMING[type]) {
            return { accentBg: 'bg-primary', iconText: 'text-primary', iconBg: 'bg-primary/10' };
        }
        return TYPE_THEMING[type];
    });

    readonly isLoan = computed(() => {
        const type = this.selectedType();
        return type ? TypeGuards.isLoanAccount(type) : false;
    });

    constructor() {
        // Reset state when opening/closing
        effect(() => {
            if (!this.isOpen()) {
                this.step.set('select-type');
                this.selectedType.set(null);
                this.accountName.set('');
                this.institutionName.set('');
                this.initialBalance.set('');
                this.error.set(null);
            }
        });
    }

    handleTypeSelect(type: AccountType): void {
        this.selectedType.set(type);
        this.step.set('enter-details');
        this.error.set(null);

        const defaultNames: Record<string, string> = {
            [AccountType.Checking]: 'Main Checking',
            [AccountType.Savings]: 'Savings',
            [AccountType.Credit]: 'Credit Card',
            [AccountType.Cash]: 'Cash'
        };
        const defaultName = defaultNames[type];
        if (defaultName) {
            this.accountName.set(defaultName);
        }
    }

    async handleCreate(): Promise<void> {
        if (!this.accountName().trim()) {
            this.error.set('Account name is required');
            return;
        }

        this.error.set(null);
        this.step.set('creating');

        try {
            const type = this.selectedType();
            if (!type) {
                this.error.set('Account type is required');
                this.step.set('select-type');
                return;
            }
            const now = new Date().toISOString() as ISODateString;
            let val = parseFloat(this.initialBalance() || '0');

            if (this.selectedType() === AccountType.Credit) {
                val = -Math.abs(val);
            } else {
                val = Math.abs(val);
            }

            const balanceCents = Math.round(val * 100);

            const newAccount: IAccount = {
                id: `acc-${Date.now()}`,
                name: this.accountName().trim(),
                type: type,
                institutionName: this.institutionName().trim(),
                clearedBalance: balanceCents,
                pendingBalance: balanceCents,
                isActive: true,
                deletedAt: null,
                createdAt: now,
                updatedAt: now
            };

            this.accountCreated.emit(newAccount);
            this.posthogService.posthog.capture('account_created', {
                account_type: type,
                has_institution_name: !!this.institutionName().trim(),
                has_initial_balance: !!this.initialBalance()
            });
            this.closed.emit();
        } catch {
            this.error.set('Failed to create account');
            this.step.set('enter-details');
        }
    }

    handleCancel(): void {
        this.closed.emit();
    }

    getTypeTheming(type: AccountType): { accentBg: string; iconText: string; iconBg: string } {
        return (
            TYPE_THEMING[type] || {
                accentBg: 'bg-primary',
                iconText: 'text-primary',
                iconBg: 'bg-primary/10'
            }
        );
    }

    // Lucide Icons
    readonly X = X;
    readonly Landmark = Landmark;
    readonly Banknote = Banknote;
    readonly CreditCard = CreditCard;
    readonly Wallet = Wallet;
    readonly Home = Home;
    readonly Car = Car;
    readonly Receipt = Receipt;
    readonly ChevronDown = ChevronDown;
    readonly ChevronUp = ChevronUp;
}

<p-dialog
    [visible]="isOpen()"
    (onHide)="closed.emit()"
    [modal]="true"
    [draggable]="false"
    [resizable]="false"
    [closable]="true"
    [style]="{ width: '500px' }"
    header="Add New Account"
    styleClass="path-logic-dialog"
>
    <ng-template #header>
        <div class="flex items-center gap-2">
            <div class="w-5 h-5 bg-primary rounded-sm flex items-center justify-center">
                <span class="text-primary-foreground font-black text-[10px]">P</span>
            </div>
            <h2 class="text-xs font-black uppercase tracking-[0.2em] text-foreground">
                Add <span class="text-primary">New Account</span>
            </h2>
        </div>
    </ng-template>

    <div class="mt-4">
        <p-stepper [value]="stepValue()">
            <p-step-list class="mb-6">
                <p-step [value]="1">Type</p-step>
                <p-step [value]="2">Details</p-step>
            </p-step-list>

            <p-step-panels>
                <!-- Step 1: Select Type -->
                <p-step-panel [value]="1">
                    <ng-template #content let-activateCallback="activateCallback">
                        <div class="space-y-6">
                            <div class="grid grid-cols-2 gap-3">
                                @for (option of primaryTypes(); track option.type) {
                                    <button
                                        (click)="handleTypeSelect(option.type)"
                                        class="group flex flex-col items-center p-4 border border-border rounded-sm hover:border-primary/50 hover:bg-primary/5 transition-all text-center outline-none focus:ring-1 focus:ring-primary"
                                    >
                                        <div
                                            [class]="
                                                'w-10 h-10 rounded-sm flex items-center justify-center mb-3 group-hover:scale-110 transition-transform ' +
                                                getTypeTheming(option.type).iconBg
                                            "
                                        >
                                            <lucide-icon
                                                [img]="option.icon"
                                                [class]="
                                                    'w-5 h-5 ' +
                                                    getTypeTheming(option.type).iconText
                                                "
                                            />
                                        </div>
                                        <span
                                            class="text-[10px] font-black uppercase tracking-widest mb-1"
                                            >{{ option.label }}</span
                                        >
                                        <span
                                            class="text-[9px] text-muted-foreground font-bold uppercase tracking-tighter opacity-60 leading-tight"
                                        >
                                            {{ option.description }}
                                        </span>
                                    </button>
                                }
                            </div>

                            <div class="pt-2">
                                <p-button
                                    (click)="showLoans.set(!showLoans())"
                                    [label]="'Loan / Liability Types'"
                                    [text]="true"
                                    [icon]="showLoans() ? 'pi pi-chevron-up' : 'pi pi-chevron-down'"
                                    iconPos="right"
                                    severity="secondary"
                                    styleClass="w-full text-[10px] font-bold uppercase tracking-widest justify-content-between"
                                ></p-button>

                                @if (showLoans()) {
                                    <div
                                        class="grid grid-cols-1 gap-2 mt-2 animate-in slide-in-from-top-2"
                                    >
                                        @for (option of loanTypes(); track option.type) {
                                            <button
                                                (click)="handleTypeSelect(option.type)"
                                                class="flex items-center gap-4 p-3 border border-border rounded-sm hover:border-amber-500/50 hover:bg-amber-500/5 transition-all text-left group"
                                            >
                                                <div
                                                    class="w-8 h-8 rounded-sm bg-amber-500/10 flex items-center justify-center group-hover:scale-110 transition-transform"
                                                >
                                                    <lucide-icon
                                                        [img]="option.icon"
                                                        class="w-4 h-4 text-amber-500"
                                                    />
                                                </div>
                                                <div>
                                                    <span
                                                        class="text-[10px] font-black uppercase tracking-widest block"
                                                        >{{ option.label }}</span
                                                    >
                                                    <span
                                                        class="text-[9px] text-muted-foreground font-bold uppercase tracking-tighter opacity-60"
                                                        >{{ option.description }}</span
                                                    >
                                                </div>
                                            </button>
                                        }
                                    </div>
                                }
                            </div>
                        </div>
                    </ng-template>
                </p-step-panel>

                <!-- Step 2: Enter Details -->
                <p-step-panel [value]="2">
                    <ng-template #content let-activateCallback="activateCallback">
                        <div class="min-h-[300px] flex flex-col">
                            @if (step() === 'creating') {
                                <div
                                    class="py-12 flex flex-col items-center justify-center gap-4 flex-1"
                                >
                                    <div
                                        class="w-10 h-10 border-2 border-primary border-t-transparent rounded-full animate-spin"
                                    ></div>
                                    <p
                                        class="text-[10px] font-black uppercase tracking-[0.3em] text-primary animate-pulse"
                                    >
                                        Initializing Ledger...
                                    </p>
                                </div>
                            } @else if (selectedType() && isLoan()) {
                                <div class="animate-in slide-in-from-bottom-4">
                                    <app-loan-details-form
                                        [type]="selectedType()!"
                                        (backClicked)="step.set('select-type')"
                                        (submitted)="accountCreated.emit($event); closed.emit()"
                                    />
                                </div>
                            } @else if (selectedType()) {
                                <div class="space-y-6">
                                    <div
                                        class="flex gap-4 p-4 bg-muted/30 rounded-sm border border-border"
                                    >
                                        <div
                                            [class]="
                                                'w-12 h-12 rounded-sm flex items-center justify-center flex-none ' +
                                                theming().iconBg
                                            "
                                        >
                                            <lucide-icon
                                                [img]="selectedOption()?.icon || Landmark"
                                                [class]="'w-6 h-6 ' + theming().iconText"
                                            />
                                        </div>
                                        <div>
                                            <h3
                                                class="text-[11px] font-black uppercase tracking-widest mb-0.5"
                                            >
                                                {{ selectedOption()?.label }}
                                            </h3>
                                            <p
                                                class="text-[10px] text-muted-foreground font-bold uppercase tracking-tighter opacity-60 leading-tight"
                                            >
                                                {{ selectedOption()?.description }}
                                            </p>
                                        </div>
                                    </div>

                                    <div class="space-y-4">
                                        <div class="space-y-1.5">
                                            <label
                                                for="account-name-input"
                                                class="text-[10px] font-black uppercase tracking-widest opacity-70"
                                                >Account Name *</label
                                            >
                                            <input
                                                id="account-name-input"
                                                [ngModel]="accountName()"
                                                (ngModelChange)="accountName.set($event)"
                                                placeholder="e.g. Chase Checking"
                                                class="w-full h-9 px-3 bg-muted/5 border border-border rounded-sm focus:outline-none focus:ring-1 focus:ring-primary text-sm font-bold uppercase transition-all"
                                            />
                                        </div>
                                        <div class="space-y-1.5">
                                            <label
                                                for="institution-name-input"
                                                class="text-[10px] font-black uppercase tracking-widest opacity-70"
                                                >Institution (Optional)</label
                                            >
                                            <input
                                                id="institution-name-input"
                                                [ngModel]="institutionName()"
                                                (ngModelChange)="institutionName.set($event)"
                                                placeholder="e.g. JPMorgan Chase"
                                                class="w-full h-9 px-3 bg-muted/5 border border-border rounded-sm focus:outline-none focus:ring-1 focus:ring-primary text-sm font-bold uppercase transition-all"
                                            />
                                        </div>
                                        <div class="space-y-1.5">
                                            <label
                                                for="starting-balance-input"
                                                class="text-[10px] font-black uppercase tracking-widest opacity-70"
                                                >Starting Balance</label
                                            >
                                            <input
                                                id="starting-balance-input"
                                                [ngModel]="initialBalance()"
                                                (ngModelChange)="initialBalance.set($event)"
                                                type="number"
                                                step="0.01"
                                                placeholder="0.00"
                                                class="w-full h-9 px-3 bg-muted/5 border border-border rounded-sm focus:outline-none focus:ring-1 focus:ring-primary text-sm font-mono font-bold transition-all"
                                            />
                                            <p
                                                class="text-[9px] text-muted-foreground italic font-bold uppercase tracking-tighter opacity-50"
                                            >
                                                {{
                                                    selectedType() === 'credit'
                                                        ? 'Enter amount owed'
                                                        : 'Current cleared balance'
                                                }}
                                            </p>
                                        </div>
                                    </div>

                                    @if (error()) {
                                        <div
                                            class="p-3 bg-destructive/10 border border-destructive/20 rounded-sm"
                                        >
                                            <p
                                                class="text-[10px] font-black uppercase text-destructive tracking-widest"
                                            >
                                                {{ error() }}
                                            </p>
                                        </div>
                                    }

                                    <div class="flex gap-3 pt-4">
                                        <p-button
                                            (click)="step.set('select-type')"
                                            label="Change Type"
                                            [text]="true"
                                            severity="secondary"
                                            class="flex-1"
                                            styleClass="w-full h-10 text-[10px] font-black uppercase tracking-widest"
                                        ></p-button>
                                        <p-button
                                            (click)="handleCreate()"
                                            label="Create Account"
                                            severity="primary"
                                            class="flex-1"
                                            styleClass="w-full h-10 text-[10px] font-black uppercase tracking-widest shadow-lg shadow-primary/20"
                                        ></p-button>
                                    </div>
                                </div>
                            }
                        </div>
                    </ng-template>
                </p-step-panel>
            </p-step-panels>
        </p-stepper>
    </div>
</p-dialog>

// apps/web/src/components/onboarding/NewAccountDialog.tsx
'use client';

import * as React from 'react';
import { useState } from 'react';
import { AccountType, type IAccount, type ISODateString, TypeGuards } from '@path-logic/core';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { cn } from '@/lib/utils';
import { Dialog, DialogContent } from '@/components/ui/dialog';
import {
    Landmark,
    Banknote,
    CreditCard,
    Wallet,
    Home,
    Car,
    Receipt,
    ChevronDown,
    ChevronUp,
} from 'lucide-react';
import { LoanDetailsForm } from './LoanDetailsForm';

interface INewAccountDialogProps {
    isOpen: boolean;
    onClose: () => void;
    onAccountCreated: (account: IAccount) => Promise<void>;
}

type WizardStep = 'select-type' | 'enter-details' | 'creating';

interface IAccountTypeOption {
    type: AccountType;
    icon: React.ComponentType<{ className?: string }>;
    label: string;
    description: string;
}

const PRIMARY_TYPES: Array<IAccountTypeOption> = [
    {
        type: AccountType.Checking,
        icon: Landmark,
        label: 'Checking',
        description: 'Daily spending & income',
    },
    {
        type: AccountType.Savings,
        icon: Banknote,
        label: 'Savings',
        description: 'Long-term goals',
    },
    {
        type: AccountType.Credit,
        icon: CreditCard,
        label: 'Credit Card',
        description: 'Track spending & debt',
    },
    {
        type: AccountType.Cash,
        icon: Wallet,
        label: 'Cash',
        description: 'Physical currency',
    },
];

const LOAN_TYPES: Array<IAccountTypeOption> = [
    {
        type: AccountType.Mortgage,
        icon: Home,
        label: 'Mortgage',
        description: 'Home loan & equity',
    },
    {
        type: AccountType.AutoLoan,
        icon: Car,
        label: 'Auto Loan',
        description: 'Vehicle financing',
    },
    {
        type: AccountType.PersonalLoan,
        icon: Receipt,
        label: 'Personal Loan',
        description: 'Unsecured debt',
    },
];

const TYPE_THEMING: Record<string, { accentBg: string; iconText: string; iconBg: string }> = {
    [AccountType.Checking]: {
        accentBg: 'bg-teal-500',
        iconText: 'text-teal-500',
        iconBg: 'bg-teal-500/10',
    },
    [AccountType.Savings]: {
        accentBg: 'bg-blue-500',
        iconText: 'text-blue-500',
        iconBg: 'bg-blue-500/10',
    },
    [AccountType.Credit]: {
        accentBg: 'bg-purple-500',
        iconText: 'text-purple-500',
        iconBg: 'bg-purple-500/10',
    },
    [AccountType.Cash]: {
        accentBg: 'bg-green-500',
        iconText: 'text-green-500',
        iconBg: 'bg-green-500/10',
    },
    [AccountType.Mortgage]: {
        accentBg: 'bg-amber-500',
        iconText: 'text-amber-500',
        iconBg: 'bg-amber-500/10',
    },
    [AccountType.AutoLoan]: {
        accentBg: 'bg-amber-500',
        iconText: 'text-amber-500',
        iconBg: 'bg-amber-500/10',
    },
    [AccountType.PersonalLoan]: {
        accentBg: 'bg-amber-500',
        iconText: 'text-amber-500',
        iconBg: 'bg-amber-500/10',
    },
};

export function NewAccountDialog({
    isOpen,
    onClose,
    onAccountCreated,
}: INewAccountDialogProps): React.JSX.Element {
    const [step, setStep] = useState<WizardStep>('select-type');
    const [selectedType, setSelectedType] = useState<AccountType | null>(null);
    const [showLoans, setShowLoans] = useState<boolean>(false);

    // Standard Form State
    const [accountName, setAccountName] = useState<string>('');
    const [institutionName, setInstitutionName] = useState<string>('');
    const [initialBalance, setInitialBalance] = useState<string>('');
    const [error, setError] = useState<string>('');

    // Reset state when opening/closing
    React.useEffect(() => {
        if (!isOpen) {
            setStep('select-type');
            setSelectedType(null);
            setAccountName('');
            setInstitutionName('');
            setInitialBalance('');
            setError('');
        }
    }, [isOpen]);

    const handleTypeSelect = (type: AccountType): void => {
        setSelectedType(type);
        setStep('enter-details');
        setError('');

        const defaultNames: Record<string, string> = {
            [AccountType.Checking]: 'Main Checking',
            [AccountType.Savings]: 'Savings',
            [AccountType.Credit]: 'Credit Card',
            [AccountType.Cash]: 'Cash',
        };
        const defaultName = defaultNames[type];
        if (defaultName) {
            setAccountName(defaultName);
        }
    };

    const handleCreate = async (): Promise<void> => {
        if (!accountName.trim()) {
            setError('Account name is required');
            return;
        }

        setError('');
        setStep('creating');

        try {
            const now: ISODateString = new Date().toISOString() as ISODateString;
            let val = parseFloat(initialBalance || '0');

            if (selectedType === AccountType.Credit) {
                val = -Math.abs(val);
            } else {
                val = Math.abs(val);
            }

            const balanceCents: number = Math.round(val * 100);

            const newAccount: IAccount = {
                id: `acc-${Date.now()}`,
                name: accountName.trim(),
                type: selectedType!,
                institutionName: institutionName.trim(),
                clearedBalance: balanceCents,
                pendingBalance: balanceCents,
                isActive: true,
                deletedAt: null,
                createdAt: now,
                updatedAt: now,
            };

            await onAccountCreated(newAccount);
            onClose();
        } catch {
            setError('Failed to create account');
            setStep('enter-details');
        }
    };

    const selectedOption = selectedType
        ? [...PRIMARY_TYPES, ...LOAN_TYPES].find(opt => opt.type === selectedType)
        : null;

    const theming = selectedType
        ? TYPE_THEMING[selectedType]
        : { accentBg: 'bg-primary', iconText: 'text-primary', iconBg: 'bg-primary/10' };

    return (
        <Dialog open={isOpen} onOpenChange={open => !open && onClose()}>
            <DialogContent className="sm:max-w-[500px] p-0 overflow-hidden bg-card border-border">
                <div className="p-6 border-b border-border bg-muted/30">
                    <div className="flex items-center gap-2 mb-1">
                        <div className="w-5 h-5 bg-primary rounded-sm flex items-center justify-center">
                            <span className="text-primary-foreground font-black text-[10px]">
                                P
                            </span>
                        </div>
                        <h2 className="text-xs font-black uppercase tracking-[0.2em] text-foreground">
                            Add <span className="text-primary">New Account</span>
                        </h2>
                    </div>
                    <p className="text-[10px] text-muted-foreground font-bold uppercase tracking-widest opacity-70">
                        {step === 'select-type'
                            ? 'Select the account classification'
                            : `Configure ${selectedOption?.label}`}
                    </p>
                </div>

                <div className="p-6">
                    {step === 'select-type' && (
                        <div className="space-y-6">
                            <div className="grid grid-cols-2 gap-3">
                                {PRIMARY_TYPES.map(option => {
                                    const Icon = option.icon;
                                    const optTheme = TYPE_THEMING[option.type] || {
                                        accentBg: 'bg-primary',
                                        iconText: 'text-primary',
                                        iconBg: 'bg-primary/10',
                                    };
                                    return (
                                        <button
                                            key={option.type}
                                            onClick={() => handleTypeSelect(option.type)}
                                            className="group flex flex-col items-center p-4 border border-border rounded-sm hover:border-primary/50 hover:bg-primary/5 transition-all text-center"
                                        >
                                            <div
                                                className={cn(
                                                    'w-10 h-10 rounded-sm flex items-center justify-center mb-3 group-hover:scale-110 transition-transform',
                                                    optTheme.iconBg,
                                                )}
                                            >
                                                <Icon
                                                    className={cn('w-5 h-5', optTheme.iconText)}
                                                />
                                            </div>
                                            <span className="text-[10px] font-black uppercase tracking-widest mb-1">
                                                {option.label}
                                            </span>
                                            <span className="text-[9px] text-muted-foreground font-bold uppercase tracking-tighter opacity-60 leading-tight">
                                                {option.description}
                                            </span>
                                        </button>
                                    );
                                })}
                            </div>

                            <div className="pt-2">
                                <button
                                    onClick={() => setShowLoans(!showLoans)}
                                    className="w-full flex items-center justify-between px-3 py-2 text-[10px] font-bold uppercase tracking-widest text-muted-foreground hover:text-foreground hover:bg-muted/50 rounded-sm transition-colors"
                                >
                                    <span>Loan / Liability Types</span>
                                    {showLoans ? (
                                        <ChevronUp className="w-3 h-3" />
                                    ) : (
                                        <ChevronDown className="w-3 h-3" />
                                    )}
                                </button>

                                {showLoans && (
                                    <div className="grid grid-cols-1 gap-2 mt-2 animate-in slide-in-from-top-2">
                                        {LOAN_TYPES.map(option => {
                                            const Icon = option.icon;
                                            return (
                                                <button
                                                    key={option.type}
                                                    onClick={() => handleTypeSelect(option.type)}
                                                    className="flex items-center gap-4 p-3 border border-border rounded-sm hover:border-amber-500/50 hover:bg-amber-500/5 transition-all text-left group"
                                                >
                                                    <div className="w-8 h-8 rounded-sm bg-amber-500/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                                                        <Icon className="w-4 h-4 text-amber-500" />
                                                    </div>
                                                    <div>
                                                        <span className="text-[10px] font-black uppercase tracking-widest block">
                                                            {option.label}
                                                        </span>
                                                        <span className="text-[9px] text-muted-foreground font-bold uppercase tracking-tighter opacity-60">
                                                            {option.description}
                                                        </span>
                                                    </div>
                                                </button>
                                            );
                                        })}
                                    </div>
                                )}
                            </div>
                        </div>
                    )}

                    {step === 'enter-details' &&
                        selectedType &&
                        !TypeGuards.isLoanAccount(selectedType) && (
                            <div className="space-y-6">
                                <div className="flex gap-4 p-4 bg-muted/30 rounded-sm border border-border">
                                    <div
                                        className={cn(
                                            'w-12 h-12 rounded-sm flex items-center justify-center flex-none',
                                            theming?.iconBg,
                                        )}
                                    >
                                        {selectedOption && (
                                            <selectedOption.icon
                                                className={cn('w-6 h-6', theming?.iconText)}
                                            />
                                        )}
                                    </div>
                                    <div>
                                        <h3 className="text-[11px] font-black uppercase tracking-widest mb-0.5">
                                            {selectedOption?.label}
                                        </h3>
                                        <p className="text-[10px] text-muted-foreground font-bold uppercase tracking-tighter opacity-60 leading-tight">
                                            {selectedOption?.description}
                                        </p>
                                    </div>
                                </div>

                                <div className="space-y-4">
                                    <div className="space-y-1.5">
                                        <Label
                                            htmlFor="dlg-account-name"
                                            className="text-[10px] font-black uppercase tracking-widest opacity-70"
                                        >
                                            Account Name *
                                        </Label>
                                        <Input
                                            id="dlg-account-name"
                                            value={accountName}
                                            onChange={e => setAccountName(e.target.value)}
                                            placeholder="e.g. Chase Checking"
                                            className="h-9 text-sm font-bold uppercase"
                                            autoFocus
                                        />
                                    </div>
                                    <div className="space-y-1.5">
                                        <Label
                                            htmlFor="dlg-institution"
                                            className="text-[10px] font-black uppercase tracking-widest opacity-70"
                                        >
                                            Institution (Optional)
                                        </Label>
                                        <Input
                                            id="dlg-institution"
                                            value={institutionName}
                                            onChange={e => setInstitutionName(e.target.value)}
                                            placeholder="e.g. JPMorgan Chase"
                                            className="h-9 text-sm font-bold uppercase"
                                        />
                                    </div>
                                    <div className="space-y-1.5">
                                        <Label
                                            htmlFor="dlg-balance"
                                            className="text-[10px] font-black uppercase tracking-widest opacity-70"
                                        >
                                            Starting Balance
                                        </Label>
                                        <Input
                                            id="dlg-balance"
                                            type="number"
                                            step="0.01"
                                            value={initialBalance}
                                            onChange={e => setInitialBalance(e.target.value)}
                                            placeholder="0.00"
                                            className="h-9 text-sm font-mono font-bold"
                                        />
                                        <p className="text-[9px] text-muted-foreground italic font-bold uppercase tracking-tighter opacity-50">
                                            {selectedType === AccountType.Credit
                                                ? 'Enter amount owed'
                                                : 'Current cleared balance'}
                                        </p>
                                    </div>
                                </div>

                                {error && (
                                    <div className="p-3 bg-destructive/10 border border-destructive/20 rounded-sm">
                                        <p className="text-[10px] font-black uppercase text-destructive tracking-widest">
                                            {error}
                                        </p>
                                    </div>
                                )}

                                <div className="flex gap-3 pt-4">
                                    <Button
                                        variant="outline"
                                        className="flex-1 h-10 text-[10px] font-black uppercase tracking-widest"
                                        onClick={() => setStep('select-type')}
                                    >
                                        Change Type
                                    </Button>
                                    <Button
                                        className="flex-1 h-10 text-[10px] font-black uppercase tracking-widest shadow-lg shadow-primary/20"
                                        onClick={handleCreate}
                                    >
                                        Create Account
                                    </Button>
                                </div>
                            </div>
                        )}

                    {step === 'enter-details' &&
                        selectedType &&
                        TypeGuards.isLoanAccount(selectedType) && (
                            <div className="animate-in slide-in-from-bottom-4">
                                <LoanDetailsForm
                                    type={selectedType}
                                    onBack={() => setStep('select-type')}
                                    onSubmit={async (acc: IAccount) => {
                                        setStep('creating');
                                        await onAccountCreated(acc);
                                        onClose();
                                    }}
                                />
                            </div>
                        )}

                    {step === 'creating' && (
                        <div className="py-12 flex flex-col items-center justify-center gap-4">
                            <div className="w-10 h-10 border-2 border-primary border-t-transparent rounded-full animate-spin"></div>
                            <p className="text-[10px] font-black uppercase tracking-[0.3em] text-primary animate-pulse">
                                Initializing Ledger...
                            </p>
                        </div>
                    )}
                </div>
            </DialogContent>
        </Dialog>
    );
}
