// apps/web/src/app/components/sync/sync-indicator/sync-indicator.component.ts
import type { OnDestroy, OnInit } from '@angular/core';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import type { TimerHandle } from '@path-logic/core';
import { AlertTriangle, Cloud, LucideAngularModule, RefreshCw } from 'lucide-angular';

import { AuthService } from '../../../services/auth/auth.service';
import { LedgerStore } from '../../../services/ledger-store/ledger.store';
import { SyncService } from '../../../services/sync/sync.service';

/**
 * Global indicator for Google Drive sync status.
 * Visualizes when the app is in-progress, idle, or has encountered an error.
 */
@Component({
    selector: 'app-sync-indicator',
    standalone: true,
    imports: [LucideAngularModule],
    templateUrl: './sync-indicator.component.html',
    styleUrl: './sync-indicator.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SyncIndicatorComponent implements OnInit, OnDestroy {
    private readonly ledgerStore: LedgerStore = inject(LedgerStore);
    private readonly syncService: SyncService = inject(SyncService);
    private readonly authService: AuthService = inject(AuthService);

    readonly CloudIcon = Cloud;
    readonly RefreshCwIcon = RefreshCw;
    readonly AlertTriangleIcon = AlertTriangle;

    private pollInterval: TimerHandle | null = null;
    readonly lastSyncTime = signal<number>(0);

    readonly syncStatus = this.ledgerStore.syncStatus;
    readonly authError = this.ledgerStore.authError;
    readonly hasLocalFallback = this.ledgerStore.hasLocalFallback;
    readonly isSyncing = this.syncService.isSyncing;

    readonly statusLabel = computed((): string => {
        const currentStatus: string = this.syncStatus();
        if (currentStatus === 'error') return 'Sync Error';
        if (currentStatus === 'pending-local') return 'Local Only';
        if (this.isSyncing()) return 'Active...';
        return 'Idle';
    });

    readonly lastSyncFormatted = computed((): string | null => {
        const time: number = this.lastSyncTime();
        if (time <= 0) return null;
        return new Date(time).toLocaleTimeString('en-US', {
            hour12: false,
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
        });
    });

    ngOnInit(): void {
        this.pollInterval = setInterval((): void => {
            const status = this.syncService.getSyncStatus();
            this.lastSyncTime.set(status.lastSyncTime);
        }, 500);
    }

    ngOnDestroy(): void {
        if (this.pollInterval) clearInterval(this.pollInterval);
    }

    /**
     * Initiates the Google Drive reconnection flow.
     */
    handleReconnect(): void {
        void this.authService.signInWithGoogle();
    }
}

// apps/web/src/components/sync/SyncIndicator.tsx
'use client';

import React, { useEffect, useState } from 'react';
import { getSyncStatus } from '@/lib/sync/syncService';
import { cn } from '@/lib/utils';
import { Cloud, RefreshCw } from 'lucide-react';

/**
 * Global indicator for Google Drive sync status.
 * Visualizes when the app is in-progress, idle, or has encountered an error.
 */
export function SyncIndicator(): React.JSX.Element {
    const [status, setStatus] = useState(getSyncStatus());

    useEffect((): (() => void) => {
        const interval: NodeJS.Timeout = setInterval((): void => {
            const currentStatus = getSyncStatus();
            setStatus((prev) => {
                if (prev.inProgress === currentStatus.inProgress &&
                    prev.lastSyncTime === currentStatus.lastSyncTime) {
                    return prev;
                }
                return currentStatus;
            });
        }, 500);

        return (): void => clearInterval(interval);
    }, []);

    const isSyncing: boolean = status.inProgress;

    return (
        <div className="flex items-center gap-4 text-[9px] font-mono text-muted-foreground uppercase">
            <div className="flex items-center gap-1.5">
                <div className="relative flex items-center justify-center">
                    <div
                        className={cn(
                            "w-1.5 h-1.5 rounded-full",
                            isSyncing ? "bg-primary animate-pulse" : "bg-emerald-500"
                        )}
                    />
                    {isSyncing && (
                        <div className="absolute w-3 h-3 border border-primary/30 rounded-full animate-ping" />
                    )}
                </div>
                <span className="flex items-center gap-1">
                    {isSyncing ? <RefreshCw className="w-2.5 h-2.5 animate-spin" /> : <Cloud className="w-2.5 h-2.5" />}
                    Cloud Sync: {isSyncing ? 'Active...' : 'Idle'}
                </span>
            </div>

            {status.lastSyncTime > 0 && (
                <span className="hidden sm:inline border-l border-border pl-4">
                    Last Backup: {new Date(status.lastSyncTime).toLocaleTimeString('en-US', {
                        hour12: false,
                        hour: '2-digit',
                        minute: '2-digit',
                        second: '2-digit'
                    })}
                </span>
            )}
        </div>
    );
}
