// app/src/app/components/sync/sync-indicator/sync-indicator.component.ts
import type { OnDestroy, OnInit } from '@angular/core';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import type { TimerHandle } from '@core';
import { AlertTriangle, Cloud, LucideAngularModule, RefreshCw } from 'lucide-angular';

import { AuthService } from '../../../services/auth/auth.service';
import { LedgerStore } from '../../../services/ledger-store/ledger.store';
import { SyncService } from '../../../services/sync/sync.service';

/**
 * Global indicator for Google Drive sync status.
 * Visualizes when the app is in-progress, idle, or has encountered an error.
 */
@Component({
    selector: 'sync-indicator',
    standalone: true,
    imports: [LucideAngularModule],
    templateUrl: './sync-indicator.component.html',
    styleUrl: './sync-indicator.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class SyncIndicatorComponent implements OnInit, OnDestroy {
    private readonly ledgerStore: LedgerStore = inject(LedgerStore);
    private readonly syncService: SyncService = inject(SyncService);
    private readonly authService: AuthService = inject(AuthService);

    readonly CloudIcon = Cloud;
    readonly RefreshCwIcon = RefreshCw;
    readonly AlertTriangleIcon = AlertTriangle;

    private pollInterval: TimerHandle | null = null;
    readonly lastSyncTime = signal<number>(0);

    readonly syncStatus = this.ledgerStore.syncStatus;
    readonly authError = this.ledgerStore.authError;
    readonly hasLocalFallback = this.ledgerStore.hasLocalFallback;
    readonly isSyncing = this.syncService.isSyncing;

    readonly statusLabel = computed((): string => {
        const currentStatus: string = this.syncStatus();
        if (currentStatus === 'error') return 'Sync Error';
        if (currentStatus === 'pending-local') return 'Local Only';
        if (this.isSyncing()) return 'Active...';
        return 'Idle';
    });

    readonly lastSyncFormatted = computed((): string | null => {
        const time: number = this.lastSyncTime();
        if (time <= 0) return null;
        return new Date(time).toLocaleTimeString('en-US', {
            hour12: false,
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit'
        });
    });

    ngOnInit(): void {
        this.pollInterval = setInterval((): void => {
            const status = this.syncService.getSyncStatus();
            this.lastSyncTime.set(status.lastSyncTime);
        }, 500);
    }

    ngOnDestroy(): void {
        if (this.pollInterval) clearInterval(this.pollInterval);
    }

    /**
     * Initiates the Google Drive reconnection flow.
     */
    handleReconnect(): void {
        void this.authService.signInWithGoogle();
    }
}

<div class="flex items-center gap-4 text-[9px] font-mono text-surface-500 uppercase">
    <div class="flex items-center gap-1.5">
        <div class="relative flex items-center justify-center">
            <!-- Synced / active -->
            @if (syncStatus() === 'synced' && !authError()) {
                <div
                    class="w-1.5 h-1.5 rounded-full"
                    [class.bg-primary]="isSyncing()"
                    [class.animate-pulse]="isSyncing()"
                    [class.bg-emerald-500]="!isSyncing()"
                ></div>
                @if (isSyncing()) {
                    <div
                        class="absolute w-3 h-3 border border-primary/30 rounded-full animate-ping"
                    ></div>
                }
            }
            <!-- Pending local or auth error with fallback -->
            @if (syncStatus() === 'pending-local' || (authError() && hasLocalFallback())) {
                <div class="w-1.5 h-1.5 rounded-full bg-amber-500 animate-pulse"></div>
            }
            <!-- Error without fallback -->
            @if (syncStatus() === 'error' && !hasLocalFallback()) {
                <div class="w-1.5 h-1.5 rounded-full bg-red-500"></div>
            }
        </div>

        <span class="flex items-center gap-1">
            @if (syncStatus() === 'error') {
                <lucide-icon
                    [img]="AlertTriangleIcon"
                    class="w-2.5 h-2.5 text-red-500"
                ></lucide-icon>
            } @else if (syncStatus() === 'pending-local') {
                <lucide-icon
                    [img]="RefreshCwIcon"
                    class="w-2.5 h-2.5 text-amber-500 animate-spin"
                ></lucide-icon>
            } @else if (isSyncing()) {
                <lucide-icon [img]="RefreshCwIcon" class="w-2.5 h-2.5 animate-spin"></lucide-icon>
            } @else {
                <lucide-icon [img]="CloudIcon" class="w-2.5 h-2.5"></lucide-icon>
            }
            Cloud Sync: {{ statusLabel() }}
        </span>
    </div>

    @if (authError()) {
        <button
            (click)="handleReconnect()"
            class="h-5 px-2 text-[8px] bg-red-500/10 hover:bg-red-500/20 text-red-500 border border-destructive/20 transition-colors uppercase font-bold rounded"
        >
            Reconnect Drive
        </button>
    }

    @if (lastSyncFormatted()) {
        <span class="hidden sm:inline border-l border-surface-200 pl-4">
            Last Backup: {{ lastSyncFormatted() }}
        </span>
    }
</div>

// apps/web/src/components/sync/SyncIndicator.tsx
'use client';

import React, { useEffect, useState } from 'react';
import { getSyncStatus } from '@/lib/sync/syncService';
import { cn } from '@/lib/utils';
import { Cloud, RefreshCw, AlertTriangle } from 'lucide-react';
import { useLedgerStore } from '@/store/ledgerStore';
import { Button } from '@/components/ui/button';

/**
 * Global indicator for Google Drive sync status.
 * Visualizes when the app is in-progress, idle, or has encountered an error.
 */
export function SyncIndicator(): React.JSX.Element {
    const authError = useLedgerStore((state) => state.authError);
    const [status, setStatus] = useState(getSyncStatus());

    const handleReconnect = async (): Promise<void> => {
        // Open sign-in in a popup to preserve in-memory state
        const width = 600;
        const height = 700;
        const left = window.screenX + (window.outerWidth - width) / 2;
        const top = window.screenY + (window.outerHeight - height) / 2;

        window.open(
            '/api/auth/signin/google?prompt=consent',
            'PathLogicAuth',
            `width=${width},height=${height},left=${left},top=${top}`
        );
    };

    useEffect((): (() => void) => {
        const interval: NodeJS.Timeout = setInterval((): void => {
            const currentStatus = getSyncStatus();
            setStatus((prev) => {
                if (prev.inProgress === currentStatus.inProgress &&
                    prev.lastSyncTime === currentStatus.lastSyncTime) {
                    return prev;
                }
                return currentStatus;
            });
        }, 500);

        return (): void => clearInterval(interval);
    }, []);

    const isSyncing: boolean = status.inProgress;

    return (
        <div className="flex items-center gap-4 text-[9px] font-mono text-muted-foreground uppercase">
            <div className="flex items-center gap-1.5">
                <div className="relative flex items-center justify-center">
                    {!authError && (
                        <>
                            <div
                                className={cn(
                                    "w-1.5 h-1.5 rounded-full",
                                    isSyncing ? "bg-primary animate-pulse" : "bg-emerald-500"
                                )}
                            />
                            {isSyncing && (
                                <div className="absolute w-3 h-3 border border-primary/30 rounded-full animate-ping" />
                            )}
                        </>
                    )}
                </div>
                <span className="flex items-center gap-1">
                    {authError ? (
                        <AlertTriangle className="w-2.5 h-2.5 text-destructive" />
                    ) : isSyncing ? (
                        <RefreshCw className="w-2.5 h-2.5 animate-spin" />
                    ) : (
                        <Cloud className="w-2.5 h-2.5" />
                    )}
                    Cloud Sync: {authError ? 'Action Required' : isSyncing ? 'Active...' : 'Idle'}
                </span>
            </div>

            {authError && (
                <Button
                    variant="ghost"
                    size="sm"
                    className="h-5 px-2 text-[8px] bg-destructive/10 hover:bg-destructive/20 text-destructive border border-destructive/20 transition-colors uppercase font-bold"
                    onClick={handleReconnect}
                >
                    Reconnect Drive
                </Button>
            )}

            {status.lastSyncTime > 0 && (
                <span className="hidden sm:inline border-l border-border pl-4">
                    Last Backup: {new Date(status.lastSyncTime).toLocaleTimeString('en-US', {
                        hour12: false,
                        hour: '2-digit',
                        minute: '2-digit',
                        second: '2-digit'
                    })}
                </span>
            )}
        </div>
    );
}
