// apps/web/src/components/layout/Footer.tsx
'use client';

import * as React from 'react';
import { SyncIndicator } from '../sync/SyncIndicator';

export function Footer(): React.JSX.Element {
    return (
        <footer className="h-8 border-t border-border bg-background flex flex-none relative z-10">
            <div className="max-w-7xl mx-auto w-full px-4 flex items-center justify-between text-[9px] font-mono text-muted-foreground uppercase">
                <SyncIndicator />
                <div>Environment: Local Engine • v4.2-Alpha</div>
            </div>
        </footer>
    );
}

// app/src/app/components/layout/footer/footer.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

import { environment } from '../../../../environments/environment';
import { SyncIndicatorComponent } from '../../sync/sync-indicator/sync-indicator.component';

/**
 * Global application footer component showing sync status and environment info.
 */
@Component({
    selector: 'footer',
    standalone: true,
    imports: [SyncIndicatorComponent],
    templateUrl: './footer.component.html',
    styleUrl: './footer.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class FooterComponent {
    /**
     * Current application environment name.
     */
    readonly appEnv: string = environment.appEnv;
}

<div class="h-8 border-t border-surface-200 bg-surface-50 flex flex-none relative z-10">
    <div
        class="max-w-7xl mx-auto w-full px-4 flex items-center justify-between text-[9px] font-mono text-surface-500 uppercase"
    >
        <sync-indicator />
        <div>Environment: {{ appEnv }} • v4.2-Alpha</div>
    </div>
</div>
