// app/src/app/components/layout/app-shell/app-shell.component.ts
import { ChangeDetectionStrategy, Component, inject, input } from '@angular/core';

import { SecurityManagerService } from '../../../services/security-manager/security-manager.service';
import { AuthOverlayComponent } from '../../auth/auth-overlay/auth-overlay.component';
import { SyncPendingBannerComponent } from '../../auth/sync-pending-banner/sync-pending-banner.component';
import { BreadcrumbNavComponent } from '../breadcrumb-nav/breadcrumb-nav.component';
import { FooterComponent } from '../footer/footer.component';
import { HeaderComponent } from '../header/header.component';
import { SecurityOverlayComponent } from '../security-overlay/security-overlay.component';

/**
 * Global application shell that provides the consistent header,
 * Bloomberg-style background, and overflow management.
 */
@Component({
    selector: 'shell',
    standalone: true,
    imports: [
        HeaderComponent,
        FooterComponent,
        BreadcrumbNavComponent,
        SecurityOverlayComponent,
        AuthOverlayComponent,
        SyncPendingBannerComponent
    ],
    templateUrl: './app-shell.component.html',
    styleUrl: './app-shell.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppShellComponent {
    private readonly securityManager: SecurityManagerService = inject(SecurityManagerService);

    /**
     * Whether the main content area should be scrollable.
     * Default: true
     */
    readonly scrollable = input<boolean>(true);

    /**
     * Whether to disable default page padding and max-width.
     * Default: false
     */
    readonly noPadding = input<boolean>(false);

    /**
     * Expose isIdle state from security manager.
     */
    readonly isIdle = this.securityManager.isIdle;

    constructor() {
        // Start monitoring user activity for security timeouts
        this.securityManager.startMonitoring();
    }

    /**
     * Resets the security activity timers.
     */
    resetTimers(): void {
        this.securityManager.resetTimers();
    }
}

<div
    class="h-screen bg-surface-50 text-surface-900 font-sans selection:bg-primary/30 overflow-hidden flex flex-col relative"
>
    <!-- Security & Auth Guardrails -->
    <security-overlay [isVisible]="isIdle()" (unlocked)="resetTimers()" />
    <auth-overlay />
    <sync-pending-banner />

    <header></header>

    <main
        class="flex-1 w-full flex flex-col min-h-0 relative"
        [class.overflow-hidden]="!scrollable()"
    >
        <breadcrumb-nav />

        <div
            class="flex-1 w-full flex flex-col"
            [class.overflow-y-auto]="scrollable()"
            [class.overflow-x-hidden]="scrollable()"
            [class.overflow-hidden]="!scrollable()"
        >
            <div
                class="w-full mx-auto flex flex-col"
                [class.p-4]="!noPadding()"
                [class.max-w-7xl]="!noPadding()"
                [class.min-h-full]="scrollable()"
                [class.h-full]="!scrollable()"
            >
                <ng-content />
            </div>
        </div>
    </main>

    <footer></footer>
</div>

// apps/web/src/components/layout/AppShell.tsx
'use client';

import * as React from 'react';
import { Header } from './Header';
import { cn } from '@/lib/utils';

import { useSecurityManager } from '@/hooks/useSecurityManager';
import { SecurityOverlay } from './SecurityOverlay';
import { BreadcrumbNav } from './BreadcrumbNav';
import { Footer } from './Footer';
import { AuthOverlay, SyncPendingBanner } from '../auth/AuthOverlay';

interface IAppShellProps {
    children: React.ReactNode;
    className?: string;
    noPadding?: boolean;
    scrollable?: boolean;
}

/**
 * Global application shell that provides the consistent header,
 * Bloomberg-style background, and overflow management.
 */
export function AppShell({
    children,
    className,
    noPadding = false,
    scrollable = true,
}: IAppShellProps): React.JSX.Element {
    const { isIdle, unlock } = useSecurityManager();

    return (
        <div className="h-screen bg-background text-foreground font-sans selection:bg-primary/30 overflow-hidden flex flex-col relative">
            <SecurityOverlay isVisible={isIdle} onUnlock={unlock} />
            <AuthOverlay />
            <SyncPendingBanner />
            <Header />
            <main className={cn('flex-1 w-full flex flex-col min-h-0 relative', className)}>
                <div className="flex-none w-full border-b border-border/50 bg-background/50 backdrop-blur-sm px-4">
                    <div className="max-w-7xl mx-auto py-2">
                        <BreadcrumbNav />
                    </div>
                </div>

                <div
                    className={cn(
                        'flex-1 w-full flex flex-col',
                        scrollable ? 'overflow-y-auto overflow-x-hidden' : 'overflow-hidden',
                    )}
                >
                    <div
                        className={cn(
                            'w-full mx-auto flex flex-col',
                            !noPadding && 'p-4 max-w-7xl',
                            scrollable ? 'min-h-full' : 'h-full',
                        )}
                    >
                        {children}
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    );
}
