// app/src/app/components/layout/security-overlay/security-overlay.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { ArrowRight, Lock, LucideAngularModule, ShieldAlert } from 'lucide-angular';

/**
 * Premium security overlay that blurs the screen when the session is idle.
 * Prevents unauthorized viewing of PII (Personally Identifiable Information).
 */
@Component({
    selector: 'security-overlay',
    standalone: true,
    imports: [LucideAngularModule],
    templateUrl: './security-overlay.component.html',
    styleUrl: './security-overlay.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class SecurityOverlayComponent {
    /**
     * Whether the overlay is visible.
     */
    readonly isVisible = input.required<boolean>();

    /**
     * Emitted when the user clicks 'Resume Session'.
     */
    readonly unlocked = output();

    readonly LockIcon = Lock;
    readonly ShieldAlertIcon = ShieldAlert;
    readonly ArrowRightIcon = ArrowRight;
}

<div
    class="fixed inset-0 z-[1200] flex items-center justify-center bg-surface-0 sm:bg-surface-50/40 sm:backdrop-blur-xl transition-all duration-500 ease-in-out opacity-0 pointer-events-none"
    role="region"
    aria-label="Session Paused Lock Screen"
    [class.opacity-100]="isVisible()"
    [class.pointer-events-auto]="isVisible()"
>
    <div
        class="w-full h-full sm:h-auto sm:max-w-md sm:mx-4 p-6 sm:p-12 rounded-none sm:rounded-3xl border-0 sm:border border-surface-200 bg-surface-0 sm:bg-surface-0/95 shadow-none sm:shadow-2xl sm:backdrop-blur-md text-center transform transition-all duration-500 delay-75 ease-out scale-100 sm:scale-95 sm:translate-y-4 opacity-0 flex flex-col justify-between sm:justify-center min-h-screen sm:min-h-[400px] overflow-y-auto"
        [class.sm:scale-100]="isVisible()"
        [class.sm:translate-y-0]="isVisible()"
        [class.opacity-100]="isVisible()"
    >
        <!-- Top Spacer on mobile / empty on desktop -->
        <div class="sm:hidden pt-8">
            <div
                class="w-14 h-14 bg-primary/10 rounded-2xl flex items-center justify-center mx-auto ring-1 ring-primary/20"
            >
                <i class="pi pi-shield text-2xl text-primary"></i>
            </div>
        </div>

        <!-- Main Body -->
        <div class="my-auto py-6 sm:py-0">
            <div
                class="hidden sm:flex w-16 h-16 bg-primary/10 rounded-2xl items-center justify-center mx-auto mb-6 ring-1 ring-primary/20"
            >
                <i class="pi pi-lock text-3xl text-primary shadow-sm"></i>
            </div>

            <div
                class="sm:hidden w-18 h-18 bg-primary/10 rounded-3xl flex items-center justify-center mx-auto mb-6 ring-1 ring-primary/20 animate-pulse"
            >
                <i class="pi pi-lock text-3xl text-primary"></i>
            </div>

            <h2 class="text-2xl sm:text-2xl font-black tracking-tight mb-3 text-surface-900">
                Session Paused
            </h2>
            <p
                class="text-surface-600 text-sm sm:text-sm mb-6 sm:mb-8 px-2 sm:px-4 leading-relaxed max-w-sm mx-auto"
            >
                Your session has been paused due to inactivity to protect your local financial data.
            </p>
        </div>

        <!-- Bottom Actions -->
        <div class="space-y-4 pb-6 sm:pb-0 w-full max-w-sm mx-auto">
            <button
                (click)="unlocked.emit()"
                aria-label="Resume Session"
                class="w-full min-h-[56px] sm:min-h-[48px] py-4 sm:py-3 px-6 rounded-2xl sm:rounded-xl text-base sm:text-md font-bold group flex items-center justify-center gap-2 transition-transform active:scale-[0.98] bg-primary text-white hover:bg-primary/90 shadow-premium cursor-pointer"
            >
                <span>Resume Session</span>
                <i
                    class="pi pi-arrow-right text-base transition-transform group-hover:translate-x-1"
                    aria-hidden="true"
                ></i>
            </button>

            <div
                class="pt-1 flex items-center justify-center gap-2 text-xs sm:text-[10px] text-surface-500 uppercase tracking-widest font-semibold"
            >
                <i class="pi pi-shield text-xs text-primary"></i>
                Secure Local-First Environment
            </div>
        </div>
    </div>
</div>

// apps/web/src/components/layout/SecurityOverlay.tsx
'use client';

import React from 'react';
import { Lock, ShieldAlert, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';

interface ISecurityOverlayProps {
    isVisible: boolean;
    onUnlock: () => void;
}

/**
 * Premium security overlay that blurs the screen when the session is idle.
 * Prevents unauthorized viewing of PII (Personally Identifiable Information).
 */
export function SecurityOverlay({ isVisible, onUnlock }: ISecurityOverlayProps): React.JSX.Element {
    if (!isVisible) return <></>;

    return (
        <div
            className={cn(
                'fixed inset-0 z-[100] flex items-center justify-center bg-background/40 backdrop-blur-xl transition-all duration-500 ease-in-out',
                isVisible ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none',
            )}
        >
            <div
                className={cn(
                    'max-w-md w-full mx-4 p-8 rounded-3xl border border-border bg-card/80 shadow-2xl backdrop-blur-md text-center transform transition-all duration-500 delay-75 ease-out',
                    isVisible
                        ? 'scale-100 translate-y-0 opacity-100'
                        : 'scale-95 translate-y-4 opacity-0',
                )}
            >
                <div className="w-16 h-16 bg-primary/10 rounded-2xl flex items-center justify-center mx-auto mb-6 ring-1 ring-primary/20">
                    <Lock className="w-8 h-8 text-primary shadow-sm" />
                </div>

                <h2 className="text-2xl font-bold tracking-tight mb-2">Session Paused</h2>
                <p className="text-muted-foreground text-sm mb-8 px-4 leading-relaxed">
                    Your session has been paused due to inactivity to protect your financial data.
                </p>

                <div className="space-y-3">
                    <Button
                        onClick={onUnlock}
                        className="w-full h-12 rounded-xl text-md font-semibold group flex items-center justify-center gap-2 transition-transform active:scale-[0.98]"
                    >
                        Resume Session
                        <ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" />
                    </Button>

                    <div className="pt-2 flex items-center justify-center gap-2 text-[10px] text-muted-foreground uppercase tracking-widest font-medium">
                        <ShieldAlert className="w-3 h-3" />
                        Secure Local-First Environment
                    </div>
                </div>
            </div>
        </div>
    );
}
