// apps/web/src/components/ledger/SplitEntryDialog.tsx
'use client';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';
import { useLedgerStore } from '@/store/ledgerStore';
import { type ISplit, KnownCategory, Money } from '@path-logic/core';
import { Calculator, Plus, Scale, Trash2 } from 'lucide-react';
import * as React from 'react';
import {
    Dialog,
    DialogContent,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';

interface ISplitEntryDialogProps {
    isOpen: boolean;
    onClose: () => void;
    totalAmount: number; // in cents
    initialSplits: Array<ISplit>;
    onSave: (splits: Array<ISplit>, newTotal?: number) => void;
}

export function SplitEntryDialog({
    isOpen,
    onClose,
    totalAmount,
    initialSplits,
    onSave,
}: ISplitEntryDialogProps): React.JSX.Element {
    const { categories } = useLedgerStore();
    const [splits, setSplits] = React.useState<Array<ISplit>>(() =>
        initialSplits.length > 0
            ? initialSplits
            : [
                  {
                      id: `split-${Date.now()}`,
                      amount: totalAmount,
                      memo: '',
                      categoryId: KnownCategory.Uncategorized,
                  },
              ],
    );

    const sumSplits = splits.reduce((sum, s) => sum + s.amount, 0);
    const difference = totalAmount - sumSplits;
    const isBalanced = difference === 0;

    const handleAddSplit = (): void => {
        setSplits([
            ...splits,
            {
                id: `split-${Date.now()}`,
                amount: 0,
                memo: '',
                categoryId: KnownCategory.Uncategorized,
            },
        ]);
    };

    const handleRemoveSplit = (id: string): void => {
        if (splits.length <= 1) return;
        setSplits(splits.filter(s => s.id !== id));
    };

    const handleUpdateSplit = (id: string, updates: Partial<ISplit>): void => {
        setSplits(splits.map(s => (s.id === id ? { ...s, ...updates } : s)));
    };

    const handleQuickBalance = (): void => {
        if (splits.length === 0) return;
        const lastSplit = splits[splits.length - 1];
        if (!lastSplit) return;
        handleUpdateSplit(lastSplit.id, { amount: lastSplit.amount + difference });
    };

    const handleSave = (): void => {
        onSave(splits);
        onClose();
    };

    const handleAdjustTotal = (): void => {
        onSave(splits, sumSplits);
        onClose();
    };

    return (
        <Dialog open={isOpen} onOpenChange={onClose}>
            <DialogContent className="max-w-2xl bg-card border-border">
                <DialogHeader>
                    <DialogTitle className="text-sm font-black uppercase tracking-widest text-primary">
                        Split Transaction Detail
                    </DialogTitle>
                </DialogHeader>

                <div className="py-4 space-y-4">
                    {/* Summary Header */}
                    <div className="flex justify-between items-center bg-accent/30 p-3 rounded-sm border border-border">
                        <div>
                            <p className="text-[9px] text-muted-foreground font-bold uppercase tracking-tighter mb-0.5">
                                Target Total
                            </p>
                            <p className="font-mono font-bold text-lg text-primary">
                                {Money.formatCurrency(totalAmount)}
                            </p>
                        </div>
                        <div className="text-right">
                            <p className="text-[9px] text-muted-foreground font-bold uppercase tracking-tighter mb-0.5">
                                Remaining
                            </p>
                            <p
                                className={cn(
                                    'font-mono font-bold text-lg',
                                    isBalanced
                                        ? 'text-emerald-500'
                                        : 'text-destructive animate-pulse',
                                )}
                            >
                                {Money.formatCurrency(difference)}
                            </p>
                        </div>
                    </div>

                    {/* Split Table */}
                    <div className="space-y-2 max-h-[400px] overflow-y-auto pr-2 scrollbar-hide">
                        {splits.map((split, index) => (
                            <div
                                key={split.id}
                                className="flex gap-3 items-center group animate-in slide-in-from-left-2"
                                style={{ animationDelay: `${index * 50}ms` }}
                            >
                                <div className="w-[180px]">
                                    <Select
                                        value={split.categoryId || KnownCategory.Uncategorized}
                                        onValueChange={value =>
                                            handleUpdateSplit(split.id, { categoryId: value })
                                        }
                                    >
                                        <SelectTrigger className="h-8 text-[10px] uppercase font-bold bg-background border-border text-muted-foreground focus:ring-1 focus:ring-primary">
                                            <SelectValue placeholder="Category" />
                                        </SelectTrigger>
                                        <SelectContent className="bg-card border-border">
                                            {categories.map(cat => (
                                                <SelectItem
                                                    key={cat.id}
                                                    value={cat.id}
                                                    className="text-[10px] uppercase font-bold"
                                                >
                                                    {cat.name}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </div>
                                <div className="flex-1">
                                    <Input
                                        placeholder="Split Memo"
                                        value={split.memo}
                                        onChange={e =>
                                            handleUpdateSplit(split.id, { memo: e.target.value })
                                        }
                                        className="bg-background border-border text-[10px] h-8 focus:ring-1 focus:ring-primary px-2"
                                    />
                                </div>
                                <div className="w-[120px]">
                                    <Input
                                        type="number"
                                        step="0.01"
                                        placeholder="0.00"
                                        value={split.amount / 100}
                                        onChange={e =>
                                            handleUpdateSplit(split.id, {
                                                amount: Money.dollarsToCents(
                                                    parseFloat(e.target.value) || 0,
                                                ),
                                            })
                                        }
                                        className="bg-background border-border text-[10px] font-mono h-8 text-right focus:ring-1 focus:ring-primary px-2"
                                    />
                                </div>
                                <Button
                                    variant="ghost"
                                    size="icon"
                                    onClick={(): void => handleRemoveSplit(split.id)}
                                    className="h-8 w-8 text-destructive hover:bg-destructive/10"
                                >
                                    <Trash2 className="w-3.5 h-3.5" />
                                </Button>
                            </div>
                        ))}
                    </div>

                    <Button
                        variant="outline"
                        onClick={handleAddSplit}
                        className="w-full border-dashed border-border text-muted-foreground hover:text-primary hover:border-primary/50 text-[10px] font-bold uppercase h-9"
                    >
                        <Plus className="w-3.5 h-3.5 mr-2" /> Add Split Line
                    </Button>
                </div>

                <DialogFooter className="gap-2 sm:gap-0">
                    {!isBalanced && (
                        <div className="flex gap-2 mr-auto">
                            <Button
                                variant="outline"
                                onClick={handleAdjustTotal}
                                className="border-primary/30 text-primary text-[9px] font-black uppercase h-8 px-3"
                            >
                                <Scale className="w-3 h-3 mr-2" /> Adjust Total to{' '}
                                {Money.formatCurrency(sumSplits)}
                            </Button>
                            <Button
                                variant="outline"
                                onClick={handleQuickBalance}
                                className="border-emerald-500/30 text-emerald-500 text-[9px] font-black uppercase h-8 px-3"
                            >
                                <Calculator className="w-3 h-3 mr-2" /> Quick Balance
                            </Button>
                        </div>
                    )}
                    <div className="flex gap-2">
                        <Button
                            variant="ghost"
                            onClick={onClose}
                            className="text-[10px] font-bold uppercase h-8 text-muted-foreground"
                        >
                            Cancel
                        </Button>
                        <Button
                            onClick={handleSave}
                            disabled={!isBalanced}
                            className="bg-primary hover:bg-primary/90 text-primary-foreground text-[10px] font-black uppercase h-8 px-6 disabled:opacity-30"
                        >
                            Confirm Splits
                        </Button>
                    </div>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}

// apps/web/src/app/components/ledger/split-entry-dialog/split-entry-dialog.component.ts
import { CommonModule } from '@angular/common';
import {
    ChangeDetectionStrategy,
    Component,
    computed,
    effect,
    inject,
    input,
    model,
    output,
    signal,
    untracked,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import type { ISplit } from '@path-logic/core';
import { KnownCategory, Money } from '@path-logic/core';
import { Calculator, LucideAngularModule, Plus, Scale, Trash2, X } from 'lucide-angular';

import { LedgerStore } from '../../../services/ledger-store/ledger.store';

/**
 * Dialog for editing split transactions.
 * Ensures penny-perfect balancing of splits against a total amount.
 */
@Component({
    selector: 'app-split-entry-dialog',
    standalone: true,
    imports: [CommonModule, FormsModule, LucideAngularModule],
    templateUrl: './split-entry-dialog.component.html',
    styleUrls: ['./split-entry-dialog.component.css'],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SplitEntryDialogComponent {
    private readonly ledgerStore = inject(LedgerStore);

    // Inputs
    readonly isOpen = model<boolean>(false);
    readonly totalAmount = input.required<number>(); // in cents
    readonly initialSplits = input<Array<ISplit>>(new Array<ISplit>());

    // Outputs
    readonly saved = output<{ splits: Array<ISplit>; newTotal?: number }>();

    // State
    readonly splits = signal<Array<ISplit>>(new Array<ISplit>());

    // Computed
    readonly categories = this.ledgerStore.categories;

    readonly sumSplits = computed(() => {
        return this.splits().reduce((sum, s) => sum + s.amount, 0);
    });

    readonly difference = computed(() => {
        return this.totalAmount() - this.sumSplits();
    });

    readonly isBalanced = computed(() => {
        return this.difference() === 0;
    });

    constructor() {
        // Sync initialSplits to splits signal when initialSplits changes
        effect(() => {
            const initial = this.initialSplits();
            const total = this.totalAmount();

            untracked(() => {
                this.splits.set([...initial]);

                // If empty, add a default balanced split
                if (this.splits().length === 0) {
                    this.splits.set([
                        {
                            id: `split-${Date.now()}`,
                            amount: total,
                            memo: '',
                            categoryId: KnownCategory.Uncategorized,
                        },
                    ]);
                }
            });
        });
    }

    // Since we use signals, we can have a manual reset method
    reset(initial: Array<ISplit>): void {
        if (initial.length > 0) {
            this.splits.set([...initial]);
        } else {
            this.splits.set(
                new Array<ISplit>({
                    id: `split-${Date.now()}`,
                    amount: this.totalAmount(),
                    memo: '',
                    categoryId: KnownCategory.Uncategorized,
                }),
            );
        }
    }

    handleAddSplit(): void {
        this.splits.update(current => [
            ...current,
            {
                id: `split-${Date.now()}`,
                amount: 0,
                memo: '',
                categoryId: KnownCategory.Uncategorized,
            },
        ]);
    }

    handleRemoveSplit(id: string): void {
        if (this.splits().length <= 1) return;
        this.splits.update(current => current.filter(s => s.id !== id));
    }

    handleUpdateSplit(id: string, updates: Partial<ISplit>): void {
        this.splits.update(current => current.map(s => (s.id === id ? { ...s, ...updates } : s)));
    }

    handleQuickBalance(): void {
        const currentSplits = this.splits();
        if (currentSplits.length === 0) return;
        const lastSplit = currentSplits[currentSplits.length - 1];
        if (!lastSplit) return;
        this.handleUpdateSplit(lastSplit.id, {
            amount: lastSplit.amount + this.difference(),
        });
    }

    handleSave(): void {
        this.saved.emit({ splits: this.splits() });
        this.isOpen.set(false);
    }

    handleAdjustTotal(): void {
        this.saved.emit({ splits: this.splits(), newTotal: this.sumSplits() });
        this.isOpen.set(false);
    }

    formatCurrency(amount: number): string {
        return Money.formatCurrency(amount);
    }

    dollarsToCents(dollars: number): number {
        return Money.dollarsToCents(dollars);
    }

    centsToDollars(cents: number): number {
        return Money.centsToDollars(cents);
    }

    onClose(): void {
        this.isOpen.set(false);
    }

    // Lucide Icons
    readonly Calculator = Calculator;
    readonly Plus = Plus;
    readonly Scale = Scale;
    readonly Trash2 = Trash2;
    readonly X = X;
}

@if (isOpen()) {
    <div
        role="dialog"
        aria-labelledby="split-dialog-title"
        class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm animate-in fade-in duration-200"
    >
        <div
            class="w-full max-w-2xl bg-card border border-border rounded-lg shadow-2xl flex flex-col overflow-hidden animate-in zoom-in-95 duration-200"
        >
            <!-- Header -->
            <div class="px-6 py-4 border-b border-border flex justify-between items-center">
                <h3
                    id="split-dialog-title"
                    class="text-sm font-black uppercase tracking-widest text-primary"
                >
                    Split Transaction Detail
                </h3>
                <button
                    (click)="onClose()"
                    aria-label="Close dialog"
                    class="text-muted-foreground hover:text-white transition-colors"
                >
                    <lucide-icon [img]="X" class="w-4 h-4" />
                </button>
            </div>

            <div class="p-6 space-y-4">
                <!-- Summary Header -->
                <div
                    class="flex justify-between items-center bg-accent/30 p-4 rounded-sm border border-border"
                >
                    <div>
                        <p
                            class="text-[9px] text-foreground/90 font-bold uppercase tracking-tighter mb-0.5"
                        >
                            Target Total
                        </p>
                        <p class="font-mono font-bold text-lg text-primary">
                            {{ formatCurrency(totalAmount()) }}
                        </p>
                    </div>
                    <div class="text-right">
                        <p
                            class="text-[9px] text-foreground/90 font-bold uppercase tracking-tighter mb-0.5"
                        >
                            Remaining
                        </p>
                        <p
                            class="font-mono font-bold text-lg"
                            [class.text-emerald-900]="isBalanced()"
                            [class.text-destructive]="!isBalanced()"
                            [class.animate-pulse]="!isBalanced()"
                        >
                            {{ formatCurrency(difference()) }}
                        </p>
                    </div>
                </div>

                <!-- Split Table -->
                <div class="space-y-2 max-h-[400px] overflow-y-auto pr-2 ledger-scroll">
                    @for (split of splits(); track split.id; let i = $index) {
                        <div
                            class="flex gap-3 items-center group animate-in slide-in-from-left-2"
                            [style.animation-delay]="i * 50 + 'ms'"
                        >
                            <div class="w-[180px]">
                                <select
                                    [ngModel]="split.categoryId ?? 'uncategorized'"
                                    (ngModelChange)="
                                        handleUpdateSplit(split.id, { categoryId: $event })
                                    "
                                    [attr.aria-label]="'Split category ' + (i + 1)"
                                    class="w-full h-8 text-[10px] uppercase font-bold bg-background border border-border rounded-md px-2 text-foreground focus:outline-none focus:ring-1 focus:ring-primary appearance-none"
                                >
                                    @for (cat of categories(); track cat.id) {
                                        <option [value]="cat.id">{{ cat.name }}</option>
                                    }
                                </select>
                            </div>
                            <div class="flex-1">
                                <input
                                    type="text"
                                    placeholder="Split Memo"
                                    [attr.aria-label]="'Split memo ' + (i + 1)"
                                    [ngModel]="split.memo"
                                    (ngModelChange)="handleUpdateSplit(split.id, { memo: $event })"
                                    class="w-full h-8 px-2 bg-background border border-border rounded-md text-[10px] focus:outline-none focus:ring-1 focus:ring-primary"
                                />
                            </div>
                            <div class="w-[120px]">
                                <input
                                    type="number"
                                    step="0.01"
                                    placeholder="0.00"
                                    [attr.aria-label]="'Split amount ' + (i + 1)"
                                    [ngModel]="centsToDollars(split.amount)"
                                    (ngModelChange)="
                                        handleUpdateSplit(split.id, {
                                            amount: dollarsToCents($event),
                                        })
                                    "
                                    class="w-full h-8 px-2 bg-background border border-border rounded-md text-[10px] font-mono text-right focus:outline-none focus:ring-1 focus:ring-primary"
                                />
                            </div>
                            <button
                                (click)="handleRemoveSplit(split.id)"
                                aria-label="Remove split line"
                                class="h-8 w-8 flex items-center justify-center text-destructive hover:bg-destructive/10 rounded-md transition-colors"
                            >
                                <lucide-icon [img]="Trash2" class="w-3.5 h-3.5" />
                            </button>
                        </div>
                    }
                </div>

                <button
                    (click)="handleAddSplit()"
                    aria-label="Add split line"
                    class="w-full border border-dashed border-border rounded-md text-foreground hover:text-primary hover:border-primary/50 text-[10px] font-bold uppercase h-9 transition-colors flex items-center justify-center gap-2"
                >
                    <lucide-icon [img]="Plus" class="w-3.5 h-3.5" />
                    Add Split Line
                </button>
            </div>

            <!-- Footer -->
            <div
                class="px-6 py-4 border-t border-border bg-muted/10 flex justify-between items-center gap-2"
            >
                @if (!isBalanced()) {
                    <div class="flex gap-2">
                        <button
                            (click)="handleAdjustTotal()"
                            aria-label="Adjust total"
                            class="border border-primary/30 bg-background text-primary text-[9px] font-black uppercase h-8 px-3 rounded-md hover:bg-primary/10 transition-colors flex items-center gap-2"
                        >
                            <lucide-icon [img]="Scale" class="w-3 h-3" />
                            Adjust Total to {{ formatCurrency(sumSplits()) }}
                        </button>
                        <button
                            (click)="handleQuickBalance()"
                            aria-label="Quick balance"
                            class="border border-emerald-700/30 bg-background text-emerald-900 text-[9px] font-black uppercase h-8 px-3 rounded-md hover:bg-emerald-700/10 transition-colors flex items-center gap-2"
                        >
                            <lucide-icon [img]="Calculator" class="w-3 h-3" />
                            Quick Balance
                        </button>
                    </div>
                } @else {
                    <div></div>
                }

                <div class="flex gap-2">
                    <button
                        (click)="onClose()"
                        class="text-[10px] font-bold uppercase h-8 px-4 text-muted-foreground hover:text-white transition-colors"
                    >
                        Cancel
                    </button>
                    <button
                        (click)="handleSave()"
                        [disabled]="!isBalanced()"
                        class="bg-primary hover:bg-primary/90 text-primary-foreground text-[10px] font-black uppercase h-8 px-6 rounded-md transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
                    >
                        Confirm Splits
                    </button>
                </div>
            </div>
        </div>
    </div>
}
