// apps/web/src/components/layout/Header.tsx
'use client';

import { type ITransaction, Money, TransactionStatus } from '@path-logic/core';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { signOut, useSession } from 'next-auth/react';
import * as React from 'react';

import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { cn } from '@/lib/utils';
import { useLedgerStore } from '@/store/ledgerStore';

export function Header(): React.JSX.Element {
    const pathname: string | null = usePathname();
    const { transactions } = useLedgerStore();
    const { data: session } = useSession();

    const clearedBalance: number = transactions
        .filter((tx: ITransaction): boolean => tx.status === TransactionStatus.Cleared)
        .reduce((sum: number, tx: ITransaction): number => sum + tx.totalAmount, 0);

    const pendingBalance: number = transactions
        .filter((tx: ITransaction): boolean => tx.status === TransactionStatus.Pending)
        .reduce((sum: number, tx: ITransaction): number => sum + tx.totalAmount, 0);

    interface INavItem {
        name: string;
        href: string;
    }

    const navItems: Array<INavItem> = [
        { name: 'Overview', href: '/' },
        { name: 'Accounts', href: '/accounts' },
        { name: 'Payees', href: '/payees' },
        { name: 'Reports', href: '#' },
        { name: 'Settings', href: '/settings' },
    ];

    return (
        <header className="border-b border-border bg-background/80 backdrop-blur-md sticky top-0 z-30">
            <div className="max-w-[1600px] mx-auto px-4 h-14 flex items-center justify-between">
                <div className="flex items-center gap-8">
                    <Link href="/" className="flex items-center gap-2 group">
                        <div className="w-6 h-6 bg-primary rounded-sm flex items-center justify-center group-hover:shadow-[0_0_10px_rgba(56,189,248,0.5)] transition-all">
                            <span className="text-primary-foreground font-black text-xs">P</span>
                        </div>
                        <h1 className="font-bold text-sm tracking-tight uppercase">
                            Path <span className="text-primary">Logic</span>
                        </h1>
                    </Link>

                    <nav className="hidden md:flex items-center gap-1">
                        {navItems.map((item: INavItem): React.JSX.Element => {
                            const isActive: boolean = pathname === item.href || (item.href !== '/' && !!pathname?.startsWith(item.href));
                            return (
                                <Link
                                    key={item.name}
                                    href={item.href}
                                    className={cn(
                                        "px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider transition-colors rounded-sm",
                                        isActive ? 'text-primary bg-primary/10' : 'text-muted-foreground hover:text-foreground hover:bg-accent'
                                    )}
                                >
                                    {item.name}
                                </Link>
                            );
                        })}
                    </nav>
                </div>

                <div className="flex items-center gap-4">
                    <div className="flex flex-col items-end">
                        <span className="text-[10px] text-muted-foreground font-bold uppercase tracking-tighter">Net Position</span>
                        <span className={cn("text-sm font-mono font-bold leading-none", clearedBalance + pendingBalance < 0 ? 'text-destructive' : 'text-emerald-500')}>
                            {Money.formatCurrency(clearedBalance + pendingBalance)}
                        </span>
                    </div>

                    <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                            <button className="w-8 h-8 rounded-full overflow-hidden border-2 border-border hover:border-primary transition-colors focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 focus:ring-offset-background">
                                {session?.user?.image ? (
                                    <img
                                        src={session.user.image}
                                        alt={session.user.name || 'User'}
                                        className="w-full h-full object-cover"
                                    />
                                ) : (
                                    <div className="w-full h-full bg-primary flex items-center justify-center">
                                        <span className="text-primary-foreground font-bold text-xs">
                                            {session?.user?.name?.charAt(0).toUpperCase() || 'U'}
                                        </span>
                                    </div>
                                )}
                            </button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end" className="bg-card border-border w-56">
                            <div className="flex items-center gap-3 px-3 py-2 border-b border-border mb-1">
                                {session?.user?.image ? (
                                    <img
                                        src={session.user.image}
                                        alt={session.user.name || 'User'}
                                        className="w-10 h-10 rounded-full object-cover border border-border"
                                    />
                                ) : (
                                    <div className="w-10 h-10 rounded-full bg-primary flex items-center justify-center">
                                        <span className="text-primary-foreground font-bold text-sm">
                                            {session?.user?.name?.charAt(0).toUpperCase() || 'U'}
                                        </span>
                                    </div>
                                )}
                                <div className="flex flex-col overflow-hidden">
                                    <span className="text-sm font-bold text-foreground truncate">
                                        {session?.user?.name || 'User'}
                                    </span>
                                    <span className="text-[10px] text-muted-foreground truncate">
                                        {session?.user?.email || ''}
                                    </span>
                                </div>
                            </div>
                            <DropdownMenuItem className="text-[10px] uppercase font-bold focus:bg-accent cursor-pointer">
                                Profile Settings
                            </DropdownMenuItem>
                            <DropdownMenuItem
                                onClick={(): void => { void signOut({ callbackUrl: '/' }); }}
                                className="text-[10px] uppercase font-bold focus:bg-accent cursor-pointer text-destructive"
                            >
                                Sign Out
                            </DropdownMenuItem>
                        </DropdownMenuContent>
                    </DropdownMenu>
                </div>
            </div>
        </header>
    );
}

// apps/web/src/app/components/layout/header/header.component.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { type ITransaction, Money, TransactionStatus } from '@path-logic/core';
import { BarChart3, CreditCard, Home, LucideAngularModule, Settings, Users } from 'lucide-angular';

import { AuthService } from '../../../services/auth/auth.service';
import { LedgerStore } from '../../../services/ledger-store/ledger.store';

/**
 * Interface for navigation items within the header.
 */
export interface INavItem {
    name: string;
    href: string;
    icon: object;
}

/**
 * Main application header component with navigation and user profile.
 */
@Component({
    selector: 'app-header',
    standalone: true,
    imports: [RouterLink, RouterLinkActive, LucideAngularModule],
    templateUrl: './header.component.html',
    styleUrl: './header.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeaderComponent {
    private readonly ledgerStore: LedgerStore = inject(LedgerStore);
    private readonly authService: AuthService = inject(AuthService);

    showUserMenu: boolean = false;

    /**
     * List of navigation links shown in the header.
     */
    readonly navItems = new Array<INavItem>(
        { name: 'Overview', href: '/', icon: Home } satisfies INavItem,
        { name: 'Accounts', href: '/accounts', icon: CreditCard } satisfies INavItem,
        { name: 'Payees', href: '/payees', icon: Users } satisfies INavItem,
        { name: 'Reports', href: '#', icon: BarChart3 } satisfies INavItem,
        { name: 'Settings', href: '/settings', icon: Settings } satisfies INavItem,
    );

    readonly netBalance = computed((): number => {
        const txs: Array<ITransaction> = this.ledgerStore.transactions();
        const cleared: number = txs
            .filter((tx: ITransaction): boolean => tx.status === TransactionStatus.Cleared)
            .reduce((sum: number, tx: ITransaction): number => sum + tx.totalAmount, 0);
        const pending: number = txs
            .filter((tx: ITransaction): boolean => tx.status === TransactionStatus.Pending)
            .reduce((sum: number, tx: ITransaction): number => sum + tx.totalAmount, 0);
        return cleared + pending;
    });

    readonly formattedNetBalance = computed((): string => Money.formatCurrency(this.netBalance()));

    readonly userName = computed(
        (): string => this.authService.currentUser()?.displayName ?? 'User',
    );

    readonly userEmail = computed((): string => this.authService.currentUser()?.email ?? '');

    readonly userPhotoUrl = computed(
        (): string | null => this.authService.currentUser()?.photoURL ?? null,
    );

    readonly userInitial = computed((): string => this.userName().charAt(0).toUpperCase());

    /**
     * Toggles the visibility of the user profile dropdown menu.
     */
    toggleUserMenu(): void {
        this.showUserMenu = !this.showUserMenu;
    }

    /**
     * Initiates the sign-out flow and closes the menu.
     */
    handleSignOut(): void {
        this.showUserMenu = false;
        void this.authService.signOut();
    }
}

<header class="border-b border-border bg-background/80 backdrop-blur-md sticky top-0 z-30">
    <div class="max-w-7xl mx-auto px-4 h-14 flex items-center justify-between">
        <div class="flex items-center gap-8">
            <a routerLink="/" class="flex items-center gap-2 group">
                <div
                    class="w-6 h-6 bg-primary rounded-sm flex items-center justify-center group-hover:shadow-[0_0_10px_rgba(56,189,248,0.5)] transition-all"
                >
                    <span class="text-primary-foreground font-black text-xs">P</span>
                </div>
                <span class="font-bold text-sm tracking-tight uppercase"> Path Logic </span>
            </a>

            <nav class="hidden md:flex items-center gap-1">
                @for (item of navItems; track item.name) {
                    <a
                        [routerLink]="item.href"
                        routerLinkActive="text-primary bg-primary/10"
                        [routerLinkActiveOptions]="{ exact: item.href === '/' }"
                        class="px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider transition-colors rounded-sm text-foreground hover:text-foreground hover:bg-accent"
                    >
                        {{ item.name }}
                    </a>
                }
            </nav>
        </div>

        <div class="flex items-center gap-4">
            <div class="flex flex-col items-end">
                <span class="text-[10px] text-foreground font-bold uppercase tracking-tighter">
                    Net Position
                </span>
                <span
                    class="text-sm font-mono font-bold leading-none"
                    [class.text-destructive]="netBalance() < 0"
                    [class.text-emerald-900]="netBalance() >= 0"
                >
                    {{ formattedNetBalance() }}
                </span>
            </div>

            <!-- User avatar / dropdown -->
            <div class="relative">
                <button
                    (click)="toggleUserMenu()"
                    aria-label="User menu"
                    [attr.aria-expanded]="showUserMenu"
                    class="w-8 h-8 rounded-full overflow-hidden border-2 border-border hover:border-primary transition-colors focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 focus:ring-offset-background"
                >
                    @if (userPhotoUrl()) {
                        <img
                            [src]="userPhotoUrl()"
                            [alt]="userName()"
                            class="w-full h-full object-cover"
                        />
                    } @else {
                        <div class="w-full h-full bg-primary flex items-center justify-center">
                            <span class="text-primary-foreground font-bold text-xs">
                                {{ userInitial() }}
                            </span>
                        </div>
                    }
                </button>

                @if (showUserMenu) {
                    <div
                        class="absolute right-0 top-full mt-1 w-56 bg-card border border-border rounded-md shadow-lg z-50"
                    >
                        <div class="flex items-center gap-3 px-3 py-2 border-b border-border mb-1">
                            @if (userPhotoUrl()) {
                                <img
                                    [src]="userPhotoUrl()"
                                    [alt]="userName()"
                                    class="w-10 h-10 rounded-full object-cover border border-border"
                                />
                            } @else {
                                <div
                                    class="w-10 h-10 rounded-full bg-primary flex items-center justify-center"
                                >
                                    <span class="text-primary-foreground font-bold text-sm">
                                        {{ userInitial() }}
                                    </span>
                                </div>
                            }
                            <div class="flex flex-col overflow-hidden">
                                <span class="text-sm font-bold text-foreground truncate">
                                    {{ userName() }}
                                </span>
                                <span class="text-[10px] text-foreground truncate">
                                    {{ userEmail() }}
                                </span>
                            </div>
                        </div>
                        <button
                            type="button"
                            class="w-full text-left px-3 py-2 text-[10px] uppercase font-bold hover:bg-accent cursor-pointer text-foreground"
                        >
                            Profile Settings
                        </button>
                        <button
                            type="button"
                            (click)="handleSignOut()"
                            class="w-full text-left px-3 py-2 text-[10px] uppercase font-bold hover:bg-accent cursor-pointer text-destructive"
                        >
                            Sign Out
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
</header>
